# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphWorkbookchartlegendallof1(Model):
    """workbookChartLegend.

    :param overlay:
    :type overlay: bool
    :param position:
    :type position: str
    :param visible:
    :type visible: bool
    :param format:
    :type format: ~users.models.MicrosoftgraphworkbookChartLegendFormat
    """

    _attribute_map = {
        'overlay': {'key': 'overlay', 'type': 'bool'},
        'position': {'key': 'position', 'type': 'str'},
        'visible': {'key': 'visible', 'type': 'bool'},
        'format': {'key': 'format', 'type': 'MicrosoftgraphworkbookChartLegendFormat'},
    }

    def __init__(self, overlay=None, position=None, visible=None, format=None):
        super(ComponentsschemasmicrosoftGraphWorkbookchartlegendallof1, self).__init__()
        self.overlay = overlay
        self.position = position
        self.visible = visible
        self.format = format
