# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphOfficegraphinsightsallof1(Model):
    """officeGraphInsights.

    :param trending:
    :type trending: list[~users.models.Microsoftgraphtrending]
    :param shared:
    :type shared: list[~users.models.MicrosoftgraphsharedInsight]
    :param used:
    :type used: list[~users.models.MicrosoftgraphusedInsight]
    """

    _attribute_map = {
        'trending': {'key': 'trending', 'type': '[Microsoftgraphtrending]'},
        'shared': {'key': 'shared', 'type': '[MicrosoftgraphsharedInsight]'},
        'used': {'key': 'used', 'type': '[MicrosoftgraphusedInsight]'},
    }

    def __init__(self, trending=None, shared=None, used=None):
        super(ComponentsschemasmicrosoftGraphOfficegraphinsightsallof1, self).__init__()
        self.trending = trending
        self.shared = shared
        self.used = used
