# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphDriveitemversionallof1(Model):
    """driveItemVersion.

    :param content:
    :type content: bytes
    :param size:
    :type size: long
    """

    _attribute_map = {
        'content': {'key': 'content', 'type': 'base64'},
        'size': {'key': 'size', 'type': 'long'},
    }

    def __init__(self, content=None, size=None):
        super(ComponentsschemasmicrosoftGraphDriveitemversionallof1, self).__init__()
        self.content = content
        self.size = size
