# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphCalendargroupallof1(Model):
    """calendarGroup.

    :param name:
    :type name: str
    :param class_id:
    :type class_id: str
    :param change_key:
    :type change_key: str
    :param calendars:
    :type calendars: list[~users.models.Microsoftgraphcalendar]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'class_id': {'key': 'classId', 'type': 'str'},
        'change_key': {'key': 'changeKey', 'type': 'str'},
        'calendars': {'key': 'calendars', 'type': '[Microsoftgraphcalendar]'},
    }

    def __init__(self, name=None, class_id=None, change_key=None, calendars=None):
        super(ComponentsschemasmicrosoftGraphCalendargroupallof1, self).__init__()
        self.name = name
        self.class_id = class_id
        self.change_key = change_key
        self.calendars = calendars
