# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphSiteallof1(Model):
    """site.

    :param display_name:
    :type display_name: str
    :param root:
    :type root: object
    :param sharepoint_ids:
    :type sharepoint_ids: ~users.models.MicrosoftgraphsharepointIds
    :param site_collection:
    :type site_collection: ~users.models.MicrosoftgraphsiteCollection
    :param analytics:
    :type analytics: ~users.models.MicrosoftgraphitemAnalytics
    :param columns:
    :type columns: list[~users.models.MicrosoftgraphcolumnDefinition]
    :param content_types:
    :type content_types: list[~users.models.MicrosoftgraphcontentType]
    :param drive:
    :type drive: ~users.models.Microsoftgraphdrive
    :param drives:
    :type drives: list[~users.models.Microsoftgraphdrive]
    :param items:
    :type items: list[~users.models.MicrosoftgraphbaseItem]
    :param lists:
    :type lists: list[~users.models.Microsoftgraphlist]
    :param pages:
    :type pages: list[~users.models.MicrosoftgraphsitePage]
    :param sites:
    :type sites: list[~users.models.Microsoftgraphsite]
    :param onenote:
    :type onenote: ~users.models.Microsoftgraphonenote
    """

    _attribute_map = {
        'display_name': {'key': 'displayName', 'type': 'str'},
        'root': {'key': 'root', 'type': 'object'},
        'sharepoint_ids': {'key': 'sharepointIds', 'type': 'MicrosoftgraphsharepointIds'},
        'site_collection': {'key': 'siteCollection', 'type': 'MicrosoftgraphsiteCollection'},
        'analytics': {'key': 'analytics', 'type': 'MicrosoftgraphitemAnalytics'},
        'columns': {'key': 'columns', 'type': '[MicrosoftgraphcolumnDefinition]'},
        'content_types': {'key': 'contentTypes', 'type': '[MicrosoftgraphcontentType]'},
        'drive': {'key': 'drive', 'type': 'Microsoftgraphdrive'},
        'drives': {'key': 'drives', 'type': '[Microsoftgraphdrive]'},
        'items': {'key': 'items', 'type': '[MicrosoftgraphbaseItem]'},
        'lists': {'key': 'lists', 'type': '[Microsoftgraphlist]'},
        'pages': {'key': 'pages', 'type': '[MicrosoftgraphsitePage]'},
        'sites': {'key': 'sites', 'type': '[Microsoftgraphsite]'},
        'onenote': {'key': 'onenote', 'type': 'Microsoftgraphonenote'},
    }

    def __init__(self, display_name=None, root=None, sharepoint_ids=None, site_collection=None, analytics=None, columns=None, content_types=None, drive=None, drives=None, items=None, lists=None, pages=None, sites=None, onenote=None):
        super(ComponentsschemasmicrosoftGraphSiteallof1, self).__init__()
        self.display_name = display_name
        self.root = root
        self.sharepoint_ids = sharepoint_ids
        self.site_collection = site_collection
        self.analytics = analytics
        self.columns = columns
        self.content_types = content_types
        self.drive = drive
        self.drives = drives
        self.items = items
        self.lists = lists
        self.pages = pages
        self.sites = sites
        self.onenote = onenote
