# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphWebaccountallof1(Model):
    """webAccount.

    :param description:
    :type description: str
    :param user_id:
    :type user_id: str
    :param service:
    :type service: ~users.models.MicrosoftgraphserviceInformation
    :param status_message:
    :type status_message: str
    :param web_url:
    :type web_url: str
    """

    _attribute_map = {
        'description': {'key': 'description', 'type': 'str'},
        'user_id': {'key': 'userId', 'type': 'str'},
        'service': {'key': 'service', 'type': 'MicrosoftgraphserviceInformation'},
        'status_message': {'key': 'statusMessage', 'type': 'str'},
        'web_url': {'key': 'webUrl', 'type': 'str'},
    }

    def __init__(self, description=None, user_id=None, service=None, status_message=None, web_url=None):
        super(ComponentsschemasmicrosoftGraphWebaccountallof1, self).__init__()
        self.description = description
        self.user_id = user_id
        self.service = service
        self.status_message = status_message
        self.web_url = web_url
