# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphItemanalyticsallof1(Model):
    """itemAnalytics.

    :param item_activity_stats:
    :type item_activity_stats:
     list[~users.models.MicrosoftgraphitemActivityStat]
    :param all_time:
    :type all_time: ~users.models.MicrosoftgraphitemActivityStat
    :param last_seven_days:
    :type last_seven_days: ~users.models.MicrosoftgraphitemActivityStat
    """

    _attribute_map = {
        'item_activity_stats': {'key': 'itemActivityStats', 'type': '[MicrosoftgraphitemActivityStat]'},
        'all_time': {'key': 'allTime', 'type': 'MicrosoftgraphitemActivityStat'},
        'last_seven_days': {'key': 'lastSevenDays', 'type': 'MicrosoftgraphitemActivityStat'},
    }

    def __init__(self, item_activity_stats=None, all_time=None, last_seven_days=None):
        super(ComponentsschemasmicrosoftGraphItemanalyticsallof1, self).__init__()
        self.item_activity_stats = item_activity_stats
        self.all_time = all_time
        self.last_seven_days = last_seven_days
