# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphWorkbookchartgridlinesformatallof1(Model):
    """workbookChartGridlinesFormat.

    :param line:
    :type line: ~users.models.MicrosoftgraphworkbookChartLineFormat
    """

    _attribute_map = {
        'line': {'key': 'line', 'type': 'MicrosoftgraphworkbookChartLineFormat'},
    }

    def __init__(self, line=None):
        super(ComponentsschemasmicrosoftGraphWorkbookchartgridlinesformatallof1, self).__init__()
        self.line = line
