# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphPostallof1(Model):
    """post.

    :param body:
    :type body: ~users.models.MicrosoftgraphitemBody
    :param received_date_time:
    :type received_date_time: datetime
    :param has_attachments:
    :type has_attachments: bool
    :param from_property:
    :type from_property: ~users.models.Microsoftgraphrecipient
    :param sender:
    :type sender: ~users.models.Microsoftgraphrecipient
    :param conversation_thread_id:
    :type conversation_thread_id: str
    :param new_participants:
    :type new_participants: list[~users.models.Microsoftgraphrecipient]
    :param conversation_id:
    :type conversation_id: str
    :param importance: Possible values include: 'low', 'normal', 'high'
    :type importance: str or ~users.models.enum
    :param in_reply_to:
    :type in_reply_to: ~users.models.Microsoftgraphpost
    :param single_value_extended_properties:
    :type single_value_extended_properties:
     list[~users.models.MicrosoftgraphsingleValueLegacyExtendedProperty]
    :param multi_value_extended_properties:
    :type multi_value_extended_properties:
     list[~users.models.MicrosoftgraphmultiValueLegacyExtendedProperty]
    :param extensions:
    :type extensions: list[~users.models.Microsoftgraphextension]
    :param attachments:
    :type attachments: list[~users.models.Microsoftgraphattachment]
    :param mentions:
    :type mentions: list[~users.models.Microsoftgraphmention]
    """

    _attribute_map = {
        'body': {'key': 'body', 'type': 'MicrosoftgraphitemBody'},
        'received_date_time': {'key': 'receivedDateTime', 'type': 'iso-8601'},
        'has_attachments': {'key': 'hasAttachments', 'type': 'bool'},
        'from_property': {'key': 'from', 'type': 'Microsoftgraphrecipient'},
        'sender': {'key': 'sender', 'type': 'Microsoftgraphrecipient'},
        'conversation_thread_id': {'key': 'conversationThreadId', 'type': 'str'},
        'new_participants': {'key': 'newParticipants', 'type': '[Microsoftgraphrecipient]'},
        'conversation_id': {'key': 'conversationId', 'type': 'str'},
        'importance': {'key': 'importance', 'type': 'str'},
        'in_reply_to': {'key': 'inReplyTo', 'type': 'Microsoftgraphpost'},
        'single_value_extended_properties': {'key': 'singleValueExtendedProperties', 'type': '[MicrosoftgraphsingleValueLegacyExtendedProperty]'},
        'multi_value_extended_properties': {'key': 'multiValueExtendedProperties', 'type': '[MicrosoftgraphmultiValueLegacyExtendedProperty]'},
        'extensions': {'key': 'extensions', 'type': '[Microsoftgraphextension]'},
        'attachments': {'key': 'attachments', 'type': '[Microsoftgraphattachment]'},
        'mentions': {'key': 'mentions', 'type': '[Microsoftgraphmention]'},
    }

    def __init__(self, body=None, received_date_time=None, has_attachments=None, from_property=None, sender=None, conversation_thread_id=None, new_participants=None, conversation_id=None, importance=None, in_reply_to=None, single_value_extended_properties=None, multi_value_extended_properties=None, extensions=None, attachments=None, mentions=None):
        super(ComponentsschemasmicrosoftGraphPostallof1, self).__init__()
        self.body = body
        self.received_date_time = received_date_time
        self.has_attachments = has_attachments
        self.from_property = from_property
        self.sender = sender
        self.conversation_thread_id = conversation_thread_id
        self.new_participants = new_participants
        self.conversation_id = conversation_id
        self.importance = importance
        self.in_reply_to = in_reply_to
        self.single_value_extended_properties = single_value_extended_properties
        self.multi_value_extended_properties = multi_value_extended_properties
        self.extensions = extensions
        self.attachments = attachments
        self.mentions = mentions
