# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphManagedappregistrationallof1(Model):
    """managedAppRegistration.

    The ManagedAppEntity is the base entity type for all other entity types
    under app management workflow.

    :param created_date_time: Date and time of creation
    :type created_date_time: datetime
    :param last_sync_date_time: Date and time of last the app synced with
     management service.
    :type last_sync_date_time: datetime
    :param application_version: App version
    :type application_version: str
    :param management_sdk_version: App management SDK version
    :type management_sdk_version: str
    :param platform_version: Operating System version
    :type platform_version: str
    :param device_type: Host device type
    :type device_type: str
    :param device_tag: App management SDK generated tag, which helps relate
     apps hosted on the same device. Not guaranteed to relate apps in all
     conditions.
    :type device_tag: str
    :param device_name: Host device name
    :type device_name: str
    :param managed_device_id: The Managed Device identifier of the host
     device. Value could be empty even when the host device is managed.
    :type managed_device_id: str
    :param azure_ad_device_id: The Azure Active Directory Device identifier of
     the host device. Value could be empty even when the host device is Azure
     Active Directory registered.
    :type azure_ad_device_id: str
    :param device_model: The device model for the current app registration
    :type device_model: str
    :param device_manufacturer: The device manufacturer for the current app
     registration
    :type device_manufacturer: str
    :param flagged_reasons: Zero or more reasons an app registration is
     flagged. E.g. app running on rooted device
    :type flagged_reasons: list[str]
    :param user_id: The user Id to who this app registration belongs.
    :type user_id: str
    :param app_identifier:
    :type app_identifier: object
    :param version: Version of the entity.
    :type version: str
    :param applied_policies:
    :type applied_policies: list[~users.models.MicrosoftgraphmanagedAppPolicy]
    :param intended_policies:
    :type intended_policies:
     list[~users.models.MicrosoftgraphmanagedAppPolicy]
    :param operations:
    :type operations: list[~users.models.MicrosoftgraphmanagedAppOperation]
    """

    _attribute_map = {
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'last_sync_date_time': {'key': 'lastSyncDateTime', 'type': 'iso-8601'},
        'application_version': {'key': 'applicationVersion', 'type': 'str'},
        'management_sdk_version': {'key': 'managementSdkVersion', 'type': 'str'},
        'platform_version': {'key': 'platformVersion', 'type': 'str'},
        'device_type': {'key': 'deviceType', 'type': 'str'},
        'device_tag': {'key': 'deviceTag', 'type': 'str'},
        'device_name': {'key': 'deviceName', 'type': 'str'},
        'managed_device_id': {'key': 'managedDeviceId', 'type': 'str'},
        'azure_ad_device_id': {'key': 'azureADDeviceId', 'type': 'str'},
        'device_model': {'key': 'deviceModel', 'type': 'str'},
        'device_manufacturer': {'key': 'deviceManufacturer', 'type': 'str'},
        'flagged_reasons': {'key': 'flaggedReasons', 'type': '[str]'},
        'user_id': {'key': 'userId', 'type': 'str'},
        'app_identifier': {'key': 'appIdentifier', 'type': 'object'},
        'version': {'key': 'version', 'type': 'str'},
        'applied_policies': {'key': 'appliedPolicies', 'type': '[MicrosoftgraphmanagedAppPolicy]'},
        'intended_policies': {'key': 'intendedPolicies', 'type': '[MicrosoftgraphmanagedAppPolicy]'},
        'operations': {'key': 'operations', 'type': '[MicrosoftgraphmanagedAppOperation]'},
    }

    def __init__(self, created_date_time=None, last_sync_date_time=None, application_version=None, management_sdk_version=None, platform_version=None, device_type=None, device_tag=None, device_name=None, managed_device_id=None, azure_ad_device_id=None, device_model=None, device_manufacturer=None, flagged_reasons=None, user_id=None, app_identifier=None, version=None, applied_policies=None, intended_policies=None, operations=None):
        super(ComponentsschemasmicrosoftGraphManagedappregistrationallof1, self).__init__()
        self.created_date_time = created_date_time
        self.last_sync_date_time = last_sync_date_time
        self.application_version = application_version
        self.management_sdk_version = management_sdk_version
        self.platform_version = platform_version
        self.device_type = device_type
        self.device_tag = device_tag
        self.device_name = device_name
        self.managed_device_id = managed_device_id
        self.azure_ad_device_id = azure_ad_device_id
        self.device_model = device_model
        self.device_manufacturer = device_manufacturer
        self.flagged_reasons = flagged_reasons
        self.user_id = user_id
        self.app_identifier = app_identifier
        self.version = version
        self.applied_policies = applied_policies
        self.intended_policies = intended_policies
        self.operations = operations
