# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphDocumentallof1(Model):
    """document.

    :param comments:
    :type comments: list[~users.models.MicrosoftgraphdocumentComment]
    """

    _attribute_map = {
        'comments': {'key': 'comments', 'type': '[MicrosoftgraphdocumentComment]'},
    }

    def __init__(self, comments=None):
        super(ComponentsschemasmicrosoftGraphDocumentallof1, self).__init__()
        self.comments = comments
