# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphUseranalyticsallof1(Model):
    """userAnalytics.

    :param settings:
    :type settings: ~users.models.Microsoftgraphsettings
    :param activity_statistics:
    :type activity_statistics:
     list[~users.models.MicrosoftgraphactivityStatistics]
    """

    _attribute_map = {
        'settings': {'key': 'settings', 'type': 'Microsoftgraphsettings'},
        'activity_statistics': {'key': 'activityStatistics', 'type': '[MicrosoftgraphactivityStatistics]'},
    }

    def __init__(self, settings=None, activity_statistics=None):
        super(ComponentsschemasmicrosoftGraphUseranalyticsallof1, self).__init__()
        self.settings = settings
        self.activity_statistics = activity_statistics
