# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphShiftallof1(Model):
    """shift.

    :param shared_shift:
    :type shared_shift: ~users.models.MicrosoftgraphshiftItem
    :param draft_shift:
    :type draft_shift: ~users.models.MicrosoftgraphshiftItem
    :param user_id:
    :type user_id: str
    :param scheduling_group_id:
    :type scheduling_group_id: str
    """

    _attribute_map = {
        'shared_shift': {'key': 'sharedShift', 'type': 'MicrosoftgraphshiftItem'},
        'draft_shift': {'key': 'draftShift', 'type': 'MicrosoftgraphshiftItem'},
        'user_id': {'key': 'userId', 'type': 'str'},
        'scheduling_group_id': {'key': 'schedulingGroupId', 'type': 'str'},
    }

    def __init__(self, shared_shift=None, draft_shift=None, user_id=None, scheduling_group_id=None):
        super(ComponentsschemasmicrosoftGraphShiftallof1, self).__init__()
        self.shared_shift = shared_shift
        self.draft_shift = draft_shift
        self.user_id = user_id
        self.scheduling_group_id = scheduling_group_id
