# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphAttendeeallof1(Model):
    """attendee.

    :param status:
    :type status: ~users.models.MicrosoftgraphresponseStatus
    :param proposed_new_time:
    :type proposed_new_time: ~users.models.MicrosoftgraphtimeSlot
    """

    _attribute_map = {
        'status': {'key': 'status', 'type': 'MicrosoftgraphresponseStatus'},
        'proposed_new_time': {'key': 'proposedNewTime', 'type': 'MicrosoftgraphtimeSlot'},
    }

    def __init__(self, status=None, proposed_new_time=None):
        super(ComponentsschemasmicrosoftGraphAttendeeallof1, self).__init__()
        self.status = status
        self.proposed_new_time = proposed_new_time
