# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphListitemallof1(Model):
    """listItem.

    :param content_type:
    :type content_type: ~users.models.MicrosoftgraphcontentTypeInfo
    :param sharepoint_ids:
    :type sharepoint_ids: ~users.models.MicrosoftgraphsharepointIds
    :param activities:
    :type activities: list[~users.models.MicrosoftgraphitemActivityOLD]
    :param analytics:
    :type analytics: ~users.models.MicrosoftgraphitemAnalytics
    :param drive_item:
    :type drive_item: ~users.models.MicrosoftgraphdriveItem
    :param fields:
    :type fields: ~users.models.MicrosoftgraphfieldValueSet
    :param versions:
    :type versions: list[~users.models.MicrosoftgraphlistItemVersion]
    """

    _attribute_map = {
        'content_type': {'key': 'contentType', 'type': 'MicrosoftgraphcontentTypeInfo'},
        'sharepoint_ids': {'key': 'sharepointIds', 'type': 'MicrosoftgraphsharepointIds'},
        'activities': {'key': 'activities', 'type': '[MicrosoftgraphitemActivityOLD]'},
        'analytics': {'key': 'analytics', 'type': 'MicrosoftgraphitemAnalytics'},
        'drive_item': {'key': 'driveItem', 'type': 'MicrosoftgraphdriveItem'},
        'fields': {'key': 'fields', 'type': 'MicrosoftgraphfieldValueSet'},
        'versions': {'key': 'versions', 'type': '[MicrosoftgraphlistItemVersion]'},
    }

    def __init__(self, content_type=None, sharepoint_ids=None, activities=None, analytics=None, drive_item=None, fields=None, versions=None):
        super(ComponentsschemasmicrosoftGraphListitemallof1, self).__init__()
        self.content_type = content_type
        self.sharepoint_ids = sharepoint_ids
        self.activities = activities
        self.analytics = analytics
        self.drive_item = drive_item
        self.fields = fields
        self.versions = versions
