# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphOpenshiftallof1(Model):
    """openShift.

    :param shared_open_shift:
    :type shared_open_shift: ~users.models.MicrosoftgraphopenShiftItem
    :param draft_open_shift:
    :type draft_open_shift: ~users.models.MicrosoftgraphopenShiftItem
    :param scheduling_group_id:
    :type scheduling_group_id: str
    """

    _attribute_map = {
        'shared_open_shift': {'key': 'sharedOpenShift', 'type': 'MicrosoftgraphopenShiftItem'},
        'draft_open_shift': {'key': 'draftOpenShift', 'type': 'MicrosoftgraphopenShiftItem'},
        'scheduling_group_id': {'key': 'schedulingGroupId', 'type': 'str'},
    }

    def __init__(self, shared_open_shift=None, draft_open_shift=None, scheduling_group_id=None):
        super(ComponentsschemasmicrosoftGraphOpenshiftallof1, self).__init__()
        self.shared_open_shift = shared_open_shift
        self.draft_open_shift = draft_open_shift
        self.scheduling_group_id = scheduling_group_id
