# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphItememailallof1(Model):
    """itemEmail.

    :param address:
    :type address: str
    :param display_name:
    :type display_name: str
    :param type: Possible values include: 'unknown', 'work', 'personal',
     'main', 'other'
    :type type: str or ~users.models.enum
    """

    _attribute_map = {
        'address': {'key': 'address', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, address=None, display_name=None, type=None):
        super(ComponentsschemasmicrosoftGraphItememailallof1, self).__init__()
        self.address = address
        self.display_name = display_name
        self.type = type
