# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphWorkbookchartseriesallof1(Model):
    """workbookChartSeries.

    :param name:
    :type name: str
    :param format:
    :type format: ~users.models.MicrosoftgraphworkbookChartSeriesFormat
    :param points:
    :type points: list[~users.models.MicrosoftgraphworkbookChartPoint]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'format': {'key': 'format', 'type': 'MicrosoftgraphworkbookChartSeriesFormat'},
        'points': {'key': 'points', 'type': '[MicrosoftgraphworkbookChartPoint]'},
    }

    def __init__(self, name=None, format=None, points=None):
        super(ComponentsschemasmicrosoftGraphWorkbookchartseriesallof1, self).__init__()
        self.name = name
        self.format = format
        self.points = points
