# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphUseraccountinformationallof1(Model):
    """userAccountInformation.

    :param age_group:
    :type age_group: str
    :param country_code:
    :type country_code: str
    :param preferred_language_tag:
    :type preferred_language_tag: ~users.models.MicrosoftgraphlocaleInfo
    :param user_principal_name:
    :type user_principal_name: str
    """

    _attribute_map = {
        'age_group': {'key': 'ageGroup', 'type': 'str'},
        'country_code': {'key': 'countryCode', 'type': 'str'},
        'preferred_language_tag': {'key': 'preferredLanguageTag', 'type': 'MicrosoftgraphlocaleInfo'},
        'user_principal_name': {'key': 'userPrincipalName', 'type': 'str'},
    }

    def __init__(self, age_group=None, country_code=None, preferred_language_tag=None, user_principal_name=None):
        super(ComponentsschemasmicrosoftGraphUseraccountinformationallof1, self).__init__()
        self.age_group = age_group
        self.country_code = country_code
        self.preferred_language_tag = preferred_language_tag
        self.user_principal_name = user_principal_name
