# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphNotebookallof1(Model):
    """notebook.

    :param is_default:
    :type is_default: bool
    :param user_role: Possible values include: 'Owner', 'Contributor',
     'Reader', 'None'
    :type user_role: str or ~users.models.enum
    :param is_shared:
    :type is_shared: bool
    :param sections_url:
    :type sections_url: str
    :param section_groups_url:
    :type section_groups_url: str
    :param links:
    :type links: ~users.models.MicrosoftgraphnotebookLinks
    :param sections:
    :type sections: list[~users.models.MicrosoftgraphonenoteSection]
    :param section_groups:
    :type section_groups: list[~users.models.MicrosoftgraphsectionGroup]
    """

    _attribute_map = {
        'is_default': {'key': 'isDefault', 'type': 'bool'},
        'user_role': {'key': 'userRole', 'type': 'str'},
        'is_shared': {'key': 'isShared', 'type': 'bool'},
        'sections_url': {'key': 'sectionsUrl', 'type': 'str'},
        'section_groups_url': {'key': 'sectionGroupsUrl', 'type': 'str'},
        'links': {'key': 'links', 'type': 'MicrosoftgraphnotebookLinks'},
        'sections': {'key': 'sections', 'type': '[MicrosoftgraphonenoteSection]'},
        'section_groups': {'key': 'sectionGroups', 'type': '[MicrosoftgraphsectionGroup]'},
    }

    def __init__(self, is_default=None, user_role=None, is_shared=None, sections_url=None, section_groups_url=None, links=None, sections=None, section_groups=None):
        super(ComponentsschemasmicrosoftGraphNotebookallof1, self).__init__()
        self.is_default = is_default
        self.user_role = user_role
        self.is_shared = is_shared
        self.sections_url = sections_url
        self.section_groups_url = section_groups_url
        self.links = links
        self.sections = sections
        self.section_groups = section_groups
