# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphOnenotepageallof1(Model):
    """onenotePage.

    :param title:
    :type title: str
    :param created_by_app_id:
    :type created_by_app_id: str
    :param links:
    :type links: ~users.models.MicrosoftgraphpageLinks
    :param content_url:
    :type content_url: str
    :param content:
    :type content: bytes
    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    :param level:
    :type level: int
    :param order:
    :type order: int
    :param user_tags:
    :type user_tags: list[str]
    :param parent_section:
    :type parent_section: ~users.models.MicrosoftgraphonenoteSection
    :param parent_notebook:
    :type parent_notebook: ~users.models.Microsoftgraphnotebook
    """

    _validation = {
        'level': {'maximum': 2147483647, 'minimum': -2147483648},
        'order': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'title': {'key': 'title', 'type': 'str'},
        'created_by_app_id': {'key': 'createdByAppId', 'type': 'str'},
        'links': {'key': 'links', 'type': 'MicrosoftgraphpageLinks'},
        'content_url': {'key': 'contentUrl', 'type': 'str'},
        'content': {'key': 'content', 'type': 'base64'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'level': {'key': 'level', 'type': 'int'},
        'order': {'key': 'order', 'type': 'int'},
        'user_tags': {'key': 'userTags', 'type': '[str]'},
        'parent_section': {'key': 'parentSection', 'type': 'MicrosoftgraphonenoteSection'},
        'parent_notebook': {'key': 'parentNotebook', 'type': 'Microsoftgraphnotebook'},
    }

    def __init__(self, title=None, created_by_app_id=None, links=None, content_url=None, content=None, last_modified_date_time=None, level=None, order=None, user_tags=None, parent_section=None, parent_notebook=None):
        super(ComponentsschemasmicrosoftGraphOnenotepageallof1, self).__init__()
        self.title = title
        self.created_by_app_id = created_by_app_id
        self.links = links
        self.content_url = content_url
        self.content = content
        self.last_modified_date_time = last_modified_date_time
        self.level = level
        self.order = order
        self.user_tags = user_tags
        self.parent_section = parent_section
        self.parent_notebook = parent_notebook
