# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphOpenshiftchangerequestallof1(Model):
    """openShiftChangeRequest.

    :param open_shift_id:
    :type open_shift_id: str
    """

    _attribute_map = {
        'open_shift_id': {'key': 'openShiftId', 'type': 'str'},
    }

    def __init__(self, open_shift_id=None):
        super(ComponentsschemasmicrosoftGraphOpenshiftchangerequestallof1, self).__init__()
        self.open_shift_id = open_shift_id
