# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphInferenceclassificationallof1(Model):
    """inferenceClassification.

    :param overrides:
    :type overrides:
     list[~users.models.MicrosoftgraphinferenceClassificationOverride]
    """

    _attribute_map = {
        'overrides': {'key': 'overrides', 'type': '[MicrosoftgraphinferenceClassificationOverride]'},
    }

    def __init__(self, overrides=None):
        super(ComponentsschemasmicrosoftGraphInferenceclassificationallof1, self).__init__()
        self.overrides = overrides
