# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphMentionallof1(Model):
    """mention.

    :param mentioned:
    :type mentioned: ~users.models.MicrosoftgraphemailAddress
    :param mention_text:
    :type mention_text: str
    :param client_reference:
    :type client_reference: str
    :param created_by:
    :type created_by: ~users.models.MicrosoftgraphemailAddress
    :param created_date_time:
    :type created_date_time: datetime
    :param server_created_date_time:
    :type server_created_date_time: datetime
    :param deep_link:
    :type deep_link: str
    :param application:
    :type application: str
    """

    _attribute_map = {
        'mentioned': {'key': 'mentioned', 'type': 'MicrosoftgraphemailAddress'},
        'mention_text': {'key': 'mentionText', 'type': 'str'},
        'client_reference': {'key': 'clientReference', 'type': 'str'},
        'created_by': {'key': 'createdBy', 'type': 'MicrosoftgraphemailAddress'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'server_created_date_time': {'key': 'serverCreatedDateTime', 'type': 'iso-8601'},
        'deep_link': {'key': 'deepLink', 'type': 'str'},
        'application': {'key': 'application', 'type': 'str'},
    }

    def __init__(self, mentioned=None, mention_text=None, client_reference=None, created_by=None, created_date_time=None, server_created_date_time=None, deep_link=None, application=None):
        super(ComponentsschemasmicrosoftGraphMentionallof1, self).__init__()
        self.mentioned = mentioned
        self.mention_text = mention_text
        self.client_reference = client_reference
        self.created_by = created_by
        self.created_date_time = created_date_time
        self.server_created_date_time = server_created_date_time
        self.deep_link = deep_link
        self.application = application
