# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphTeamsappdefinitionallof1(Model):
    """teamsAppDefinition.

    :param teams_app_id:
    :type teams_app_id: str
    :param display_name:
    :type display_name: str
    :param version:
    :type version: str
    """

    _attribute_map = {
        'teams_app_id': {'key': 'teamsAppId', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
    }

    def __init__(self, teams_app_id=None, display_name=None, version=None):
        super(ComponentsschemasmicrosoftGraphTeamsappdefinitionallof1, self).__init__()
        self.teams_app_id = teams_app_id
        self.display_name = display_name
        self.version = version
