# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphGrouplifecyclepolicyallof1(Model):
    """groupLifecyclePolicy.

    :param group_lifetime_in_days:
    :type group_lifetime_in_days: int
    :param managed_group_types:
    :type managed_group_types: str
    :param alternate_notification_emails:
    :type alternate_notification_emails: str
    """

    _validation = {
        'group_lifetime_in_days': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'group_lifetime_in_days': {'key': 'groupLifetimeInDays', 'type': 'int'},
        'managed_group_types': {'key': 'managedGroupTypes', 'type': 'str'},
        'alternate_notification_emails': {'key': 'alternateNotificationEmails', 'type': 'str'},
    }

    def __init__(self, group_lifetime_in_days=None, managed_group_types=None, alternate_notification_emails=None):
        super(ComponentsschemasmicrosoftGraphGrouplifecyclepolicyallof1, self).__init__()
        self.group_lifetime_in_days = group_lifetime_in_days
        self.managed_group_types = managed_group_types
        self.alternate_notification_emails = alternate_notification_emails
