# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphProjectparticipationallof1(Model):
    """projectParticipation.

    :param categories:
    :type categories: list[str]
    :param client:
    :type client: ~users.models.MicrosoftgraphcompanyDetail
    :param display_name:
    :type display_name: str
    :param detail:
    :type detail: ~users.models.MicrosoftgraphpositionDetail
    :param colleagues:
    :type colleagues: list[~users.models.MicrosoftgraphrelatedPerson]
    :param sponsors:
    :type sponsors: list[~users.models.MicrosoftgraphrelatedPerson]
    """

    _attribute_map = {
        'categories': {'key': 'categories', 'type': '[str]'},
        'client': {'key': 'client', 'type': 'MicrosoftgraphcompanyDetail'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'detail': {'key': 'detail', 'type': 'MicrosoftgraphpositionDetail'},
        'colleagues': {'key': 'colleagues', 'type': '[MicrosoftgraphrelatedPerson]'},
        'sponsors': {'key': 'sponsors', 'type': '[MicrosoftgraphrelatedPerson]'},
    }

    def __init__(self, categories=None, client=None, display_name=None, detail=None, colleagues=None, sponsors=None):
        super(ComponentsschemasmicrosoftGraphProjectparticipationallof1, self).__init__()
        self.categories = categories
        self.client = client
        self.display_name = display_name
        self.detail = detail
        self.colleagues = colleagues
        self.sponsors = sponsors
