# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphTimeoffallof1(Model):
    """timeOff.

    :param shared_time_off:
    :type shared_time_off: ~users.models.MicrosoftgraphtimeOffItem
    :param draft_time_off:
    :type draft_time_off: ~users.models.MicrosoftgraphtimeOffItem
    :param user_id:
    :type user_id: str
    """

    _attribute_map = {
        'shared_time_off': {'key': 'sharedTimeOff', 'type': 'MicrosoftgraphtimeOffItem'},
        'draft_time_off': {'key': 'draftTimeOff', 'type': 'MicrosoftgraphtimeOffItem'},
        'user_id': {'key': 'userId', 'type': 'str'},
    }

    def __init__(self, shared_time_off=None, draft_time_off=None, user_id=None):
        super(ComponentsschemasmicrosoftGraphTimeoffallof1, self).__init__()
        self.shared_time_off = shared_time_off
        self.draft_time_off = draft_time_off
        self.user_id = user_id
