# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphBaseitemversionallof1(Model):
    """baseItemVersion.

    :param last_modified_by:
    :type last_modified_by: ~users.models.MicrosoftgraphidentitySet
    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    :param publication:
    :type publication: ~users.models.MicrosoftgraphpublicationFacet
    """

    _attribute_map = {
        'last_modified_by': {'key': 'lastModifiedBy', 'type': 'MicrosoftgraphidentitySet'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'publication': {'key': 'publication', 'type': 'MicrosoftgraphpublicationFacet'},
    }

    def __init__(self, last_modified_by=None, last_modified_date_time=None, publication=None):
        super(ComponentsschemasmicrosoftGraphBaseitemversionallof1, self).__init__()
        self.last_modified_by = last_modified_by
        self.last_modified_date_time = last_modified_date_time
        self.publication = publication
