# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphPlannergroupallof1(Model):
    """plannerGroup.

    :param plans:
    :type plans: list[~users.models.MicrosoftgraphplannerPlan]
    """

    _attribute_map = {
        'plans': {'key': 'plans', 'type': '[MicrosoftgraphplannerPlan]'},
    }

    def __init__(self, plans=None):
        super(ComponentsschemasmicrosoftGraphPlannergroupallof1, self).__init__()
        self.plans = plans
