# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphWorkbookchartgridlinesallof1(Model):
    """workbookChartGridlines.

    :param visible:
    :type visible: bool
    :param format:
    :type format: ~users.models.MicrosoftgraphworkbookChartGridlinesFormat
    """

    _attribute_map = {
        'visible': {'key': 'visible', 'type': 'bool'},
        'format': {'key': 'format', 'type': 'MicrosoftgraphworkbookChartGridlinesFormat'},
    }

    def __init__(self, visible=None, format=None):
        super(ComponentsschemasmicrosoftGraphWorkbookchartgridlinesallof1, self).__init__()
        self.visible = visible
        self.format = format
