# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphWorkbookchartaxistitleformatallof1(Model):
    """workbookChartAxisTitleFormat.

    :param font:
    :type font: ~users.models.MicrosoftgraphworkbookChartFont
    """

    _attribute_map = {
        'font': {'key': 'font', 'type': 'MicrosoftgraphworkbookChartFont'},
    }

    def __init__(self, font=None):
        super(ComponentsschemasmicrosoftGraphWorkbookchartaxistitleformatallof1, self).__init__()
        self.font = font
