# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphAttachmentallof1(Model):
    """attachment.

    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    :param name:
    :type name: str
    :param content_type:
    :type content_type: str
    :param size:
    :type size: int
    :param is_inline:
    :type is_inline: bool
    """

    _validation = {
        'size': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'name': {'key': 'name', 'type': 'str'},
        'content_type': {'key': 'contentType', 'type': 'str'},
        'size': {'key': 'size', 'type': 'int'},
        'is_inline': {'key': 'isInline', 'type': 'bool'},
    }

    def __init__(self, last_modified_date_time=None, name=None, content_type=None, size=None, is_inline=None):
        super(ComponentsschemasmicrosoftGraphAttachmentallof1, self).__init__()
        self.last_modified_date_time = last_modified_date_time
        self.name = name
        self.content_type = content_type
        self.size = size
        self.is_inline = is_inline
