# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphCalendarallof1(Model):
    """calendar.

    :param name:
    :type name: str
    :param color: Possible values include: 'lightBlue', 'lightGreen',
     'lightOrange', 'lightGray', 'lightYellow', 'lightTeal', 'lightPink',
     'lightBrown', 'lightRed', 'maxColor', 'auto'
    :type color: str or ~users.models.enum
    :param hex_color:
    :type hex_color: str
    :param is_default_calendar:
    :type is_default_calendar: bool
    :param change_key:
    :type change_key: str
    :param can_share:
    :type can_share: bool
    :param can_view_private_items:
    :type can_view_private_items: bool
    :param is_shared:
    :type is_shared: bool
    :param is_shared_with_me:
    :type is_shared_with_me: bool
    :param can_edit:
    :type can_edit: bool
    :param owner:
    :type owner: ~users.models.MicrosoftgraphemailAddress
    :param allowed_online_meeting_providers:
    :type allowed_online_meeting_providers: list[str]
    :param default_online_meeting_provider: Possible values include:
     'unknown', 'skypeForBusiness', 'skypeForConsumer', 'teamsForBusiness'
    :type default_online_meeting_provider: str or ~users.models.enum
    :param is_tallying_responses:
    :type is_tallying_responses: bool
    :param is_removable:
    :type is_removable: bool
    :param single_value_extended_properties:
    :type single_value_extended_properties:
     list[~users.models.MicrosoftgraphsingleValueLegacyExtendedProperty]
    :param multi_value_extended_properties:
    :type multi_value_extended_properties:
     list[~users.models.MicrosoftgraphmultiValueLegacyExtendedProperty]
    :param calendar_permissions:
    :type calendar_permissions:
     list[~users.models.MicrosoftgraphcalendarPermission]
    :param events:
    :type events: list[~users.models.Microsoftgraphevent]
    :param calendar_view:
    :type calendar_view: list[~users.models.Microsoftgraphevent]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'color': {'key': 'color', 'type': 'str'},
        'hex_color': {'key': 'hexColor', 'type': 'str'},
        'is_default_calendar': {'key': 'isDefaultCalendar', 'type': 'bool'},
        'change_key': {'key': 'changeKey', 'type': 'str'},
        'can_share': {'key': 'canShare', 'type': 'bool'},
        'can_view_private_items': {'key': 'canViewPrivateItems', 'type': 'bool'},
        'is_shared': {'key': 'isShared', 'type': 'bool'},
        'is_shared_with_me': {'key': 'isSharedWithMe', 'type': 'bool'},
        'can_edit': {'key': 'canEdit', 'type': 'bool'},
        'owner': {'key': 'owner', 'type': 'MicrosoftgraphemailAddress'},
        'allowed_online_meeting_providers': {'key': 'allowedOnlineMeetingProviders', 'type': '[str]'},
        'default_online_meeting_provider': {'key': 'defaultOnlineMeetingProvider', 'type': 'str'},
        'is_tallying_responses': {'key': 'isTallyingResponses', 'type': 'bool'},
        'is_removable': {'key': 'isRemovable', 'type': 'bool'},
        'single_value_extended_properties': {'key': 'singleValueExtendedProperties', 'type': '[MicrosoftgraphsingleValueLegacyExtendedProperty]'},
        'multi_value_extended_properties': {'key': 'multiValueExtendedProperties', 'type': '[MicrosoftgraphmultiValueLegacyExtendedProperty]'},
        'calendar_permissions': {'key': 'calendarPermissions', 'type': '[MicrosoftgraphcalendarPermission]'},
        'events': {'key': 'events', 'type': '[Microsoftgraphevent]'},
        'calendar_view': {'key': 'calendarView', 'type': '[Microsoftgraphevent]'},
    }

    def __init__(self, name=None, color=None, hex_color=None, is_default_calendar=None, change_key=None, can_share=None, can_view_private_items=None, is_shared=None, is_shared_with_me=None, can_edit=None, owner=None, allowed_online_meeting_providers=None, default_online_meeting_provider=None, is_tallying_responses=None, is_removable=None, single_value_extended_properties=None, multi_value_extended_properties=None, calendar_permissions=None, events=None, calendar_view=None):
        super(ComponentsschemasmicrosoftGraphCalendarallof1, self).__init__()
        self.name = name
        self.color = color
        self.hex_color = hex_color
        self.is_default_calendar = is_default_calendar
        self.change_key = change_key
        self.can_share = can_share
        self.can_view_private_items = can_view_private_items
        self.is_shared = is_shared
        self.is_shared_with_me = is_shared_with_me
        self.can_edit = can_edit
        self.owner = owner
        self.allowed_online_meeting_providers = allowed_online_meeting_providers
        self.default_online_meeting_provider = default_online_meeting_provider
        self.is_tallying_responses = is_tallying_responses
        self.is_removable = is_removable
        self.single_value_extended_properties = single_value_extended_properties
        self.multi_value_extended_properties = multi_value_extended_properties
        self.calendar_permissions = calendar_permissions
        self.events = events
        self.calendar_view = calendar_view
