# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphResourcespecificpermissiongrantallof1(Model):
    """resourceSpecificPermissionGrant.

    Represents an Azure Active Directory object. The directoryObject type is
    the base type for many other directory entity types.

    :param client_id:
    :type client_id: str
    :param client_app_id:
    :type client_app_id: str
    :param resource_app_id:
    :type resource_app_id: str
    :param permission_type:
    :type permission_type: str
    :param permission:
    :type permission: str
    """

    _attribute_map = {
        'client_id': {'key': 'clientId', 'type': 'str'},
        'client_app_id': {'key': 'clientAppId', 'type': 'str'},
        'resource_app_id': {'key': 'resourceAppId', 'type': 'str'},
        'permission_type': {'key': 'permissionType', 'type': 'str'},
        'permission': {'key': 'permission', 'type': 'str'},
    }

    def __init__(self, client_id=None, client_app_id=None, resource_app_id=None, permission_type=None, permission=None):
        super(ComponentsschemasmicrosoftGraphResourcespecificpermissiongrantallof1, self).__init__()
        self.client_id = client_id
        self.client_app_id = client_app_id
        self.resource_app_id = resource_app_id
        self.permission_type = permission_type
        self.permission = permission
