# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ComponentsschemasmicrosoftGraphInformationprotectionpolicyallof1(Model):
    """informationProtectionPolicy.

    :param labels:
    :type labels: list[~users.models.MicrosoftgraphinformationProtectionLabel]
    """

    _attribute_map = {
        'labels': {'key': 'labels', 'type': '[MicrosoftgraphinformationProtectionLabel]'},
    }

    def __init__(self, labels=None):
        super(ComponentsschemasmicrosoftGraphInformationprotectionpolicyallof1, self).__init__()
        self.labels = labels
