# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdeviceHealthAttestationState(Model):
    """deviceHealthAttestationState.

    :param last_update_date_time: The Timestamp of the last update.
    :type last_update_date_time: str
    :param content_namespace_url: The DHA report version. (Namespace version)
    :type content_namespace_url: str
    :param device_health_attestation_status: The DHA report version.
     (Namespace version)
    :type device_health_attestation_status: str
    :param content_version: The HealthAttestation state schema version
    :type content_version: str
    :param issued_date_time: The DateTime when device was evaluated or issued
     to MDM
    :type issued_date_time: datetime
    :param attestation_identity_key: TWhen an Attestation Identity Key (AIK)
     is present on a device, it indicates that the device has an endorsement
     key (EK) certificate.
    :type attestation_identity_key: str
    :param reset_count: The number of times a PC device has hibernated or
     resumed
    :type reset_count: long
    :param restart_count: The number of times a PC device has rebooted
    :type restart_count: long
    :param data_excution_policy: DEP Policy defines a set of hardware and
     software technologies that perform additional checks on memory
    :type data_excution_policy: str
    :param bit_locker_status: On or Off of BitLocker Drive Encryption
    :type bit_locker_status: str
    :param boot_manager_version: The version of the Boot Manager
    :type boot_manager_version: str
    :param code_integrity_check_version: The version of the Boot Manager
    :type code_integrity_check_version: str
    :param secure_boot: When Secure Boot is enabled, the core components must
     have the correct cryptographic signatures
    :type secure_boot: str
    :param boot_debugging: When bootDebugging is enabled, the device is used
     in development and testing
    :type boot_debugging: str
    :param operating_system_kernel_debugging: When
     operatingSystemKernelDebugging is enabled, the device is used in
     development and testing
    :type operating_system_kernel_debugging: str
    :param code_integrity:  When code integrity is enabled, code execution is
     restricted to integrity verified code
    :type code_integrity: str
    :param test_signing: When test signing is allowed, the device does not
     enforce signature validation during boot
    :type test_signing: str
    :param safe_mode: Safe mode is a troubleshooting option for Windows that
     starts your computer in a limited state
    :type safe_mode: str
    :param windows_pe: Operating system running with limited services that is
     used to prepare a computer for Windows
    :type windows_pe: str
    :param early_launch_anti_malware_driver_protection: ELAM provides
     protection for the computers in your network when they start up
    :type early_launch_anti_malware_driver_protection: str
    :param virtual_secure_mode: VSM is a container that protects high value
     assets from a compromised kernel
    :type virtual_secure_mode: str
    :param pcr_hash_algorithm: Informational attribute that identifies the
     HASH algorithm that was used by TPM
    :type pcr_hash_algorithm: str
    :param boot_app_security_version: The security version number of the Boot
     Application
    :type boot_app_security_version: str
    :param boot_manager_security_version: The security version number of the
     Boot Application
    :type boot_manager_security_version: str
    :param tpm_version: The security version number of the Boot Application
    :type tpm_version: str
    :param pcr0: The measurement that is captured in PCR[0]
    :type pcr0: str
    :param secure_boot_configuration_policy_finger_print: Fingerprint of the
     Custom Secure Boot Configuration Policy
    :type secure_boot_configuration_policy_finger_print: str
    :param code_integrity_policy: The Code Integrity policy that is
     controlling the security of the boot environment
    :type code_integrity_policy: str
    :param boot_revision_list_info: The Boot Revision List that was loaded
     during initial boot on the attested device
    :type boot_revision_list_info: str
    :param operating_system_rev_list_info: The Operating System Revision List
     that was loaded during initial boot on the attested device
    :type operating_system_rev_list_info: str
    :param health_status_mismatch_info: This attribute appears if DHA-Service
     detects an integrity issue
    :type health_status_mismatch_info: str
    :param health_attestation_supported_status: This attribute indicates if
     DHA is supported for the device
    :type health_attestation_supported_status: str
    """

    _attribute_map = {
        'last_update_date_time': {'key': 'lastUpdateDateTime', 'type': 'str'},
        'content_namespace_url': {'key': 'contentNamespaceUrl', 'type': 'str'},
        'device_health_attestation_status': {'key': 'deviceHealthAttestationStatus', 'type': 'str'},
        'content_version': {'key': 'contentVersion', 'type': 'str'},
        'issued_date_time': {'key': 'issuedDateTime', 'type': 'iso-8601'},
        'attestation_identity_key': {'key': 'attestationIdentityKey', 'type': 'str'},
        'reset_count': {'key': 'resetCount', 'type': 'long'},
        'restart_count': {'key': 'restartCount', 'type': 'long'},
        'data_excution_policy': {'key': 'dataExcutionPolicy', 'type': 'str'},
        'bit_locker_status': {'key': 'bitLockerStatus', 'type': 'str'},
        'boot_manager_version': {'key': 'bootManagerVersion', 'type': 'str'},
        'code_integrity_check_version': {'key': 'codeIntegrityCheckVersion', 'type': 'str'},
        'secure_boot': {'key': 'secureBoot', 'type': 'str'},
        'boot_debugging': {'key': 'bootDebugging', 'type': 'str'},
        'operating_system_kernel_debugging': {'key': 'operatingSystemKernelDebugging', 'type': 'str'},
        'code_integrity': {'key': 'codeIntegrity', 'type': 'str'},
        'test_signing': {'key': 'testSigning', 'type': 'str'},
        'safe_mode': {'key': 'safeMode', 'type': 'str'},
        'windows_pe': {'key': 'windowsPE', 'type': 'str'},
        'early_launch_anti_malware_driver_protection': {'key': 'earlyLaunchAntiMalwareDriverProtection', 'type': 'str'},
        'virtual_secure_mode': {'key': 'virtualSecureMode', 'type': 'str'},
        'pcr_hash_algorithm': {'key': 'pcrHashAlgorithm', 'type': 'str'},
        'boot_app_security_version': {'key': 'bootAppSecurityVersion', 'type': 'str'},
        'boot_manager_security_version': {'key': 'bootManagerSecurityVersion', 'type': 'str'},
        'tpm_version': {'key': 'tpmVersion', 'type': 'str'},
        'pcr0': {'key': 'pcr0', 'type': 'str'},
        'secure_boot_configuration_policy_finger_print': {'key': 'secureBootConfigurationPolicyFingerPrint', 'type': 'str'},
        'code_integrity_policy': {'key': 'codeIntegrityPolicy', 'type': 'str'},
        'boot_revision_list_info': {'key': 'bootRevisionListInfo', 'type': 'str'},
        'operating_system_rev_list_info': {'key': 'operatingSystemRevListInfo', 'type': 'str'},
        'health_status_mismatch_info': {'key': 'healthStatusMismatchInfo', 'type': 'str'},
        'health_attestation_supported_status': {'key': 'healthAttestationSupportedStatus', 'type': 'str'},
    }

    def __init__(self, last_update_date_time=None, content_namespace_url=None, device_health_attestation_status=None, content_version=None, issued_date_time=None, attestation_identity_key=None, reset_count=None, restart_count=None, data_excution_policy=None, bit_locker_status=None, boot_manager_version=None, code_integrity_check_version=None, secure_boot=None, boot_debugging=None, operating_system_kernel_debugging=None, code_integrity=None, test_signing=None, safe_mode=None, windows_pe=None, early_launch_anti_malware_driver_protection=None, virtual_secure_mode=None, pcr_hash_algorithm=None, boot_app_security_version=None, boot_manager_security_version=None, tpm_version=None, pcr0=None, secure_boot_configuration_policy_finger_print=None, code_integrity_policy=None, boot_revision_list_info=None, operating_system_rev_list_info=None, health_status_mismatch_info=None, health_attestation_supported_status=None):
        super(MicrosoftgraphdeviceHealthAttestationState, self).__init__()
        self.last_update_date_time = last_update_date_time
        self.content_namespace_url = content_namespace_url
        self.device_health_attestation_status = device_health_attestation_status
        self.content_version = content_version
        self.issued_date_time = issued_date_time
        self.attestation_identity_key = attestation_identity_key
        self.reset_count = reset_count
        self.restart_count = restart_count
        self.data_excution_policy = data_excution_policy
        self.bit_locker_status = bit_locker_status
        self.boot_manager_version = boot_manager_version
        self.code_integrity_check_version = code_integrity_check_version
        self.secure_boot = secure_boot
        self.boot_debugging = boot_debugging
        self.operating_system_kernel_debugging = operating_system_kernel_debugging
        self.code_integrity = code_integrity
        self.test_signing = test_signing
        self.safe_mode = safe_mode
        self.windows_pe = windows_pe
        self.early_launch_anti_malware_driver_protection = early_launch_anti_malware_driver_protection
        self.virtual_secure_mode = virtual_secure_mode
        self.pcr_hash_algorithm = pcr_hash_algorithm
        self.boot_app_security_version = boot_app_security_version
        self.boot_manager_security_version = boot_manager_security_version
        self.tpm_version = tpm_version
        self.pcr0 = pcr0
        self.secure_boot_configuration_policy_finger_print = secure_boot_configuration_policy_finger_print
        self.code_integrity_policy = code_integrity_policy
        self.boot_revision_list_info = boot_revision_list_info
        self.operating_system_rev_list_info = operating_system_rev_list_info
        self.health_status_mismatch_info = health_status_mismatch_info
        self.health_attestation_supported_status = health_attestation_supported_status
