# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Microsoftgraphnotebook(Model):
    """Microsoftgraphnotebook.

    :param id:
    :type id: str
    :param self:
    :type self: str
    :param created_date_time:
    :type created_date_time: datetime
    :param display_name:
    :type display_name: str
    :param created_by:
    :type created_by: ~users.models.MicrosoftgraphidentitySet
    :param last_modified_by:
    :type last_modified_by: ~users.models.MicrosoftgraphidentitySet
    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    :param is_default:
    :type is_default: bool
    :param user_role: Possible values include: 'Owner', 'Contributor',
     'Reader', 'None'
    :type user_role: str or ~users.models.enum
    :param is_shared:
    :type is_shared: bool
    :param sections_url:
    :type sections_url: str
    :param section_groups_url:
    :type section_groups_url: str
    :param links:
    :type links: ~users.models.MicrosoftgraphnotebookLinks
    :param sections:
    :type sections: list[~users.models.MicrosoftgraphonenoteSection]
    :param section_groups:
    :type section_groups: list[~users.models.MicrosoftgraphsectionGroup]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'self': {'key': 'self', 'type': 'str'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'created_by': {'key': 'createdBy', 'type': 'MicrosoftgraphidentitySet'},
        'last_modified_by': {'key': 'lastModifiedBy', 'type': 'MicrosoftgraphidentitySet'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'is_default': {'key': 'isDefault', 'type': 'bool'},
        'user_role': {'key': 'userRole', 'type': 'str'},
        'is_shared': {'key': 'isShared', 'type': 'bool'},
        'sections_url': {'key': 'sectionsUrl', 'type': 'str'},
        'section_groups_url': {'key': 'sectionGroupsUrl', 'type': 'str'},
        'links': {'key': 'links', 'type': 'MicrosoftgraphnotebookLinks'},
        'sections': {'key': 'sections', 'type': '[MicrosoftgraphonenoteSection]'},
        'section_groups': {'key': 'sectionGroups', 'type': '[MicrosoftgraphsectionGroup]'},
    }

    def __init__(self, id=None, self=None, created_date_time=None, display_name=None, created_by=None, last_modified_by=None, last_modified_date_time=None, is_default=None, user_role=None, is_shared=None, sections_url=None, section_groups_url=None, links=None, sections=None, section_groups=None):
        super(Microsoftgraphnotebook, self).__init__()
        self.id = id
        self.self = self
        self.created_date_time = created_date_time
        self.display_name = display_name
        self.created_by = created_by
        self.last_modified_by = last_modified_by
        self.last_modified_date_time = last_modified_date_time
        self.is_default = is_default
        self.user_role = user_role
        self.is_shared = is_shared
        self.sections_url = sections_url
        self.section_groups_url = section_groups_url
        self.links = links
        self.sections = sections
        self.section_groups = section_groups
