# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphoutlookGeoCoordinates(Model):
    """outlookGeoCoordinates.

    :param altitude:
    :type altitude: float
    :param latitude:
    :type latitude: float
    :param longitude:
    :type longitude: float
    :param accuracy:
    :type accuracy: float
    :param altitude_accuracy:
    :type altitude_accuracy: float
    """

    _attribute_map = {
        'altitude': {'key': 'altitude', 'type': 'float'},
        'latitude': {'key': 'latitude', 'type': 'float'},
        'longitude': {'key': 'longitude', 'type': 'float'},
        'accuracy': {'key': 'accuracy', 'type': 'float'},
        'altitude_accuracy': {'key': 'altitudeAccuracy', 'type': 'float'},
    }

    def __init__(self, altitude=None, latitude=None, longitude=None, accuracy=None, altitude_accuracy=None):
        super(MicrosoftgraphoutlookGeoCoordinates, self).__init__()
        self.altitude = altitude
        self.latitude = latitude
        self.longitude = longitude
        self.accuracy = accuracy
        self.altitude_accuracy = altitude_accuracy
