# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphrelatedPerson(Model):
    """relatedPerson.

    :param display_name:
    :type display_name: str
    :param relationship: Possible values include: 'manager', 'colleague',
     'directReport', 'dotLineReport', 'assistant', 'dotLineManager',
     'alternateContact', 'friend', 'spouse', 'sibling', 'child', 'parent',
     'sponsor', 'emergencyContact', 'other', 'unknownFutureValue'
    :type relationship: str or ~users.models.enum
    :param user_principal_name:
    :type user_principal_name: str
    """

    _attribute_map = {
        'display_name': {'key': 'displayName', 'type': 'str'},
        'relationship': {'key': 'relationship', 'type': 'str'},
        'user_principal_name': {'key': 'userPrincipalName', 'type': 'str'},
    }

    def __init__(self, display_name=None, relationship=None, user_principal_name=None):
        super(MicrosoftgraphrelatedPerson, self).__init__()
        self.display_name = display_name
        self.relationship = relationship
        self.user_principal_name = user_principal_name
