# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookApplication(Model):
    """MicrosoftgraphworkbookApplication.

    :param id:
    :type id: str
    :param calculation_mode:
    :type calculation_mode: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'calculation_mode': {'key': 'calculationMode', 'type': 'str'},
    }

    def __init__(self, id=None, calculation_mode=None):
        super(MicrosoftgraphworkbookApplication, self).__init__()
        self.id = id
        self.calculation_mode = calculation_mode
