# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookSortField(Model):
    """workbookSortField.

    :param ascending:
    :type ascending: bool
    :param color:
    :type color: str
    :param data_option:
    :type data_option: str
    :param icon:
    :type icon: ~users.models.MicrosoftgraphworkbookIcon
    :param key:
    :type key: int
    :param sort_on:
    :type sort_on: str
    """

    _validation = {
        'key': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'ascending': {'key': 'ascending', 'type': 'bool'},
        'color': {'key': 'color', 'type': 'str'},
        'data_option': {'key': 'dataOption', 'type': 'str'},
        'icon': {'key': 'icon', 'type': 'MicrosoftgraphworkbookIcon'},
        'key': {'key': 'key', 'type': 'int'},
        'sort_on': {'key': 'sortOn', 'type': 'str'},
    }

    def __init__(self, ascending=None, color=None, data_option=None, icon=None, key=None, sort_on=None):
        super(MicrosoftgraphworkbookSortField, self).__init__()
        self.ascending = ascending
        self.color = color
        self.data_option = data_option
        self.icon = icon
        self.key = key
        self.sort_on = sort_on
