# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphplannerPlanDetails(Model):
    """MicrosoftgraphplannerPlanDetails.

    :param id:
    :type id: str
    :param shared_with:
    :type shared_with: object
    :param category_descriptions:
    :type category_descriptions:
     ~users.models.MicrosoftgraphplannerCategoryDescriptions
    :param context_details:
    :type context_details: object
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'shared_with': {'key': 'sharedWith', 'type': 'object'},
        'category_descriptions': {'key': 'categoryDescriptions', 'type': 'MicrosoftgraphplannerCategoryDescriptions'},
        'context_details': {'key': 'contextDetails', 'type': 'object'},
    }

    def __init__(self, id=None, shared_with=None, category_descriptions=None, context_details=None):
        super(MicrosoftgraphplannerPlanDetails, self).__init__()
        self.id = id
        self.shared_with = shared_with
        self.category_descriptions = category_descriptions
        self.context_details = context_details
