# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphsensitivityLabel(Model):
    """MicrosoftgraphsensitivityLabel.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param display_name:
    :type display_name: str
    :param description:
    :type description: str
    :param tool_tip:
    :type tool_tip: str
    :param is_endpoint_protection_enabled:
    :type is_endpoint_protection_enabled: bool
    :param is_default:
    :type is_default: bool
    :param application_mode: Possible values include: 'manual', 'automatic',
     'recommended'
    :type application_mode: str or ~users.models.enum
    :param label_actions:
    :type label_actions: list[~users.models.MicrosoftgraphlabelActionBase]
    :param assigned_policies:
    :type assigned_policies: list[~users.models.MicrosoftgraphlabelPolicy]
    :param priority:
    :type priority: int
    :param sublabels:
    :type sublabels: list[~users.models.MicrosoftgraphsensitivityLabel]
    """

    _validation = {
        'priority': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'tool_tip': {'key': 'toolTip', 'type': 'str'},
        'is_endpoint_protection_enabled': {'key': 'isEndpointProtectionEnabled', 'type': 'bool'},
        'is_default': {'key': 'isDefault', 'type': 'bool'},
        'application_mode': {'key': 'applicationMode', 'type': 'str'},
        'label_actions': {'key': 'labelActions', 'type': '[MicrosoftgraphlabelActionBase]'},
        'assigned_policies': {'key': 'assignedPolicies', 'type': '[MicrosoftgraphlabelPolicy]'},
        'priority': {'key': 'priority', 'type': 'int'},
        'sublabels': {'key': 'sublabels', 'type': '[MicrosoftgraphsensitivityLabel]'},
    }

    def __init__(self, id=None, name=None, display_name=None, description=None, tool_tip=None, is_endpoint_protection_enabled=None, is_default=None, application_mode=None, label_actions=None, assigned_policies=None, priority=None, sublabels=None):
        super(MicrosoftgraphsensitivityLabel, self).__init__()
        self.id = id
        self.name = name
        self.display_name = display_name
        self.description = description
        self.tool_tip = tool_tip
        self.is_endpoint_protection_enabled = is_endpoint_protection_enabled
        self.is_default = is_default
        self.application_mode = application_mode
        self.label_actions = label_actions
        self.assigned_policies = assigned_policies
        self.priority = priority
        self.sublabels = sublabels
