# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdeviceKey(Model):
    """deviceKey.

    :param key_type:
    :type key_type: str
    :param key_material:
    :type key_material: bytes
    :param device_id:
    :type device_id: str
    """

    _attribute_map = {
        'key_type': {'key': 'keyType', 'type': 'str'},
        'key_material': {'key': 'keyMaterial', 'type': 'base64'},
        'device_id': {'key': 'deviceId', 'type': 'str'},
    }

    def __init__(self, key_type=None, key_material=None, device_id=None):
        super(MicrosoftgraphdeviceKey, self).__init__()
        self.key_type = key_type
        self.key_material = key_material
        self.device_id = device_id
