# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphchatMessageMention(Model):
    """chatMessageMention.

    :param id:
    :type id: int
    :param mention_text:
    :type mention_text: str
    :param mentioned:
    :type mentioned: ~users.models.MicrosoftgraphidentitySet
    """

    _validation = {
        'id': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'int'},
        'mention_text': {'key': 'mentionText', 'type': 'str'},
        'mentioned': {'key': 'mentioned', 'type': 'MicrosoftgraphidentitySet'},
    }

    def __init__(self, id=None, mention_text=None, mentioned=None):
        super(MicrosoftgraphchatMessageMention, self).__init__()
        self.id = id
        self.mention_text = mention_text
        self.mentioned = mentioned
