# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookChartTitle(Model):
    """MicrosoftgraphworkbookChartTitle.

    :param id:
    :type id: str
    :param overlay:
    :type overlay: bool
    :param text:
    :type text: str
    :param visible:
    :type visible: bool
    :param format:
    :type format: ~users.models.MicrosoftgraphworkbookChartTitleFormat
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'overlay': {'key': 'overlay', 'type': 'bool'},
        'text': {'key': 'text', 'type': 'str'},
        'visible': {'key': 'visible', 'type': 'bool'},
        'format': {'key': 'format', 'type': 'MicrosoftgraphworkbookChartTitleFormat'},
    }

    def __init__(self, id=None, overlay=None, text=None, visible=None, format=None):
        super(MicrosoftgraphworkbookChartTitle, self).__init__()
        self.id = id
        self.overlay = overlay
        self.text = text
        self.visible = visible
        self.format = format
