# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Microsoftgraphhashes(Model):
    """hashes.

    :param crc32_hash:
    :type crc32_hash: str
    :param quick_xor_hash:
    :type quick_xor_hash: str
    :param sha1_hash:
    :type sha1_hash: str
    :param sha256_hash:
    :type sha256_hash: str
    """

    _attribute_map = {
        'crc32_hash': {'key': 'crc32Hash', 'type': 'str'},
        'quick_xor_hash': {'key': 'quickXorHash', 'type': 'str'},
        'sha1_hash': {'key': 'sha1Hash', 'type': 'str'},
        'sha256_hash': {'key': 'sha256Hash', 'type': 'str'},
    }

    def __init__(self, crc32_hash=None, quick_xor_hash=None, sha1_hash=None, sha256_hash=None):
        super(Microsoftgraphhashes, self).__init__()
        self.crc32_hash = crc32_hash
        self.quick_xor_hash = quick_xor_hash
        self.sha1_hash = sha1_hash
        self.sha256_hash = sha256_hash
