# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdriveItemVersion(Model):
    """MicrosoftgraphdriveItemVersion.

    :param id:
    :type id: str
    :param last_modified_by:
    :type last_modified_by: ~users.models.MicrosoftgraphidentitySet
    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    :param publication:
    :type publication: ~users.models.MicrosoftgraphpublicationFacet
    :param content:
    :type content: bytes
    :param size:
    :type size: long
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'last_modified_by': {'key': 'lastModifiedBy', 'type': 'MicrosoftgraphidentitySet'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'publication': {'key': 'publication', 'type': 'MicrosoftgraphpublicationFacet'},
        'content': {'key': 'content', 'type': 'base64'},
        'size': {'key': 'size', 'type': 'long'},
    }

    def __init__(self, id=None, last_modified_by=None, last_modified_date_time=None, publication=None, content=None, size=None):
        super(MicrosoftgraphdriveItemVersion, self).__init__()
        self.id = id
        self.last_modified_by = last_modified_by
        self.last_modified_date_time = last_modified_date_time
        self.publication = publication
        self.content = content
        self.size = size
