# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Microsoftgraphsettings(Model):
    """settings.

    :param has_license:
    :type has_license: bool
    :param has_opted_out:
    :type has_opted_out: bool
    :param has_graph_mailbox:
    :type has_graph_mailbox: bool
    """

    _attribute_map = {
        'has_license': {'key': 'hasLicense', 'type': 'bool'},
        'has_opted_out': {'key': 'hasOptedOut', 'type': 'bool'},
        'has_graph_mailbox': {'key': 'hasGraphMailbox', 'type': 'bool'},
    }

    def __init__(self, has_license=None, has_opted_out=None, has_graph_mailbox=None):
        super(Microsoftgraphsettings, self).__init__()
        self.has_license = has_license
        self.has_opted_out = has_opted_out
        self.has_graph_mailbox = has_graph_mailbox
