# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphthumbnailSet(Model):
    """MicrosoftgraphthumbnailSet.

    :param id:
    :type id: str
    :param large:
    :type large: ~users.models.Microsoftgraphthumbnail
    :param medium:
    :type medium: ~users.models.Microsoftgraphthumbnail
    :param small:
    :type small: ~users.models.Microsoftgraphthumbnail
    :param source:
    :type source: ~users.models.Microsoftgraphthumbnail
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'large': {'key': 'large', 'type': 'Microsoftgraphthumbnail'},
        'medium': {'key': 'medium', 'type': 'Microsoftgraphthumbnail'},
        'small': {'key': 'small', 'type': 'Microsoftgraphthumbnail'},
        'source': {'key': 'source', 'type': 'Microsoftgraphthumbnail'},
    }

    def __init__(self, id=None, large=None, medium=None, small=None, source=None):
        super(MicrosoftgraphthumbnailSet, self).__init__()
        self.id = id
        self.large = large
        self.medium = medium
        self.small = small
        self.source = source
