# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphonPremisesProvisioningError(Model):
    """onPremisesProvisioningError.

    :param value:
    :type value: str
    :param category:
    :type category: str
    :param property_causing_error:
    :type property_causing_error: str
    :param occurred_date_time:
    :type occurred_date_time: datetime
    """

    _attribute_map = {
        'value': {'key': 'value', 'type': 'str'},
        'category': {'key': 'category', 'type': 'str'},
        'property_causing_error': {'key': 'propertyCausingError', 'type': 'str'},
        'occurred_date_time': {'key': 'occurredDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, value=None, category=None, property_causing_error=None, occurred_date_time=None):
        super(MicrosoftgraphonPremisesProvisioningError, self).__init__()
        self.value = value
        self.category = category
        self.property_causing_error = property_causing_error
        self.occurred_date_time = occurred_date_time
