# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Microsoftgraphpresence(Model):
    """Microsoftgraphpresence.

    :param id:
    :type id: str
    :param availability:
    :type availability: str
    :param activity:
    :type activity: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'availability': {'key': 'availability', 'type': 'str'},
        'activity': {'key': 'activity', 'type': 'str'},
    }

    def __init__(self, id=None, availability=None, activity=None):
        super(Microsoftgraphpresence, self).__init__()
        self.id = id
        self.availability = availability
        self.activity = activity
