# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphonlineMeetingInfo(Model):
    """onlineMeetingInfo.

    :param join_url:
    :type join_url: str
    :param conference_id:
    :type conference_id: str
    :param toll_number:
    :type toll_number: str
    :param toll_free_numbers:
    :type toll_free_numbers: list[str]
    :param quick_dial:
    :type quick_dial: str
    :param phones:
    :type phones: list[~users.models.Microsoftgraphphone]
    """

    _attribute_map = {
        'join_url': {'key': 'joinUrl', 'type': 'str'},
        'conference_id': {'key': 'conferenceId', 'type': 'str'},
        'toll_number': {'key': 'tollNumber', 'type': 'str'},
        'toll_free_numbers': {'key': 'tollFreeNumbers', 'type': '[str]'},
        'quick_dial': {'key': 'quickDial', 'type': 'str'},
        'phones': {'key': 'phones', 'type': '[Microsoftgraphphone]'},
    }

    def __init__(self, join_url=None, conference_id=None, toll_number=None, toll_free_numbers=None, quick_dial=None, phones=None):
        super(MicrosoftgraphonlineMeetingInfo, self).__init__()
        self.join_url = join_url
        self.conference_id = conference_id
        self.toll_number = toll_number
        self.toll_free_numbers = toll_free_numbers
        self.quick_dial = quick_dial
        self.phones = phones
