# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookTableRow(Model):
    """MicrosoftgraphworkbookTableRow.

    :param id:
    :type id: str
    :param index:
    :type index: int
    :param values:
    :type values: object
    """

    _validation = {
        'index': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'index': {'key': 'index', 'type': 'int'},
        'values': {'key': 'values', 'type': 'object'},
    }

    def __init__(self, id=None, index=None, values=None):
        super(MicrosoftgraphworkbookTableRow, self).__init__()
        self.id = id
        self.index = index
        self.values = values
