# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphyomiPersonName(Model):
    """yomiPersonName.

    :param display_name:
    :type display_name: str
    :param first:
    :type first: str
    :param maiden:
    :type maiden: str
    :param middle:
    :type middle: str
    :param last:
    :type last: str
    """

    _attribute_map = {
        'display_name': {'key': 'displayName', 'type': 'str'},
        'first': {'key': 'first', 'type': 'str'},
        'maiden': {'key': 'maiden', 'type': 'str'},
        'middle': {'key': 'middle', 'type': 'str'},
        'last': {'key': 'last', 'type': 'str'},
    }

    def __init__(self, display_name=None, first=None, maiden=None, middle=None, last=None):
        super(MicrosoftgraphyomiPersonName, self).__init__()
        self.display_name = display_name
        self.first = first
        self.maiden = maiden
        self.middle = middle
        self.last = last
