# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphmeetingParticipants(Model):
    """meetingParticipants.

    :param organizer:
    :type organizer: ~users.models.MicrosoftgraphmeetingParticipantInfo
    :param attendees:
    :type attendees: list[~users.models.MicrosoftgraphmeetingParticipantInfo]
    :param producers:
    :type producers: list[~users.models.MicrosoftgraphmeetingParticipantInfo]
    :param contributors:
    :type contributors:
     list[~users.models.MicrosoftgraphmeetingParticipantInfo]
    """

    _attribute_map = {
        'organizer': {'key': 'organizer', 'type': 'MicrosoftgraphmeetingParticipantInfo'},
        'attendees': {'key': 'attendees', 'type': '[MicrosoftgraphmeetingParticipantInfo]'},
        'producers': {'key': 'producers', 'type': '[MicrosoftgraphmeetingParticipantInfo]'},
        'contributors': {'key': 'contributors', 'type': '[MicrosoftgraphmeetingParticipantInfo]'},
    }

    def __init__(self, organizer=None, attendees=None, producers=None, contributors=None):
        super(MicrosoftgraphmeetingParticipants, self).__init__()
        self.organizer = organizer
        self.attendees = attendees
        self.producers = producers
        self.contributors = contributors
