# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgrapheducationalActivityDetail(Model):
    """educationalActivityDetail.

    :param abbreviation:
    :type abbreviation: str
    :param activities:
    :type activities: str
    :param awards:
    :type awards: str
    :param description:
    :type description: str
    :param display_name:
    :type display_name: str
    :param fields_of_study:
    :type fields_of_study: str
    :param grade:
    :type grade: str
    :param notes:
    :type notes: str
    :param web_url:
    :type web_url: str
    """

    _attribute_map = {
        'abbreviation': {'key': 'abbreviation', 'type': 'str'},
        'activities': {'key': 'activities', 'type': 'str'},
        'awards': {'key': 'awards', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'fields_of_study': {'key': 'fieldsOfStudy', 'type': 'str'},
        'grade': {'key': 'grade', 'type': 'str'},
        'notes': {'key': 'notes', 'type': 'str'},
        'web_url': {'key': 'webUrl', 'type': 'str'},
    }

    def __init__(self, abbreviation=None, activities=None, awards=None, description=None, display_name=None, fields_of_study=None, grade=None, notes=None, web_url=None):
        super(MicrosoftgrapheducationalActivityDetail, self).__init__()
        self.abbreviation = abbreviation
        self.activities = activities
        self.awards = awards
        self.description = description
        self.display_name = display_name
        self.fields_of_study = fields_of_study
        self.grade = grade
        self.notes = notes
        self.web_url = web_url
