# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphcommentAction(Model):
    """commentAction.

    :param is_reply:
    :type is_reply: bool
    :param parent_author:
    :type parent_author: ~users.models.MicrosoftgraphidentitySet
    :param participants:
    :type participants: list[~users.models.MicrosoftgraphidentitySet]
    """

    _attribute_map = {
        'is_reply': {'key': 'isReply', 'type': 'bool'},
        'parent_author': {'key': 'parentAuthor', 'type': 'MicrosoftgraphidentitySet'},
        'participants': {'key': 'participants', 'type': '[MicrosoftgraphidentitySet]'},
    }

    def __init__(self, is_reply=None, parent_author=None, participants=None):
        super(MicrosoftgraphcommentAction, self).__init__()
        self.is_reply = is_reply
        self.parent_author = parent_author
        self.participants = participants
