# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphchoiceColumn(Model):
    """choiceColumn.

    :param allow_text_entry:
    :type allow_text_entry: bool
    :param choices:
    :type choices: list[str]
    :param display_as:
    :type display_as: str
    """

    _attribute_map = {
        'allow_text_entry': {'key': 'allowTextEntry', 'type': 'bool'},
        'choices': {'key': 'choices', 'type': '[str]'},
        'display_as': {'key': 'displayAs', 'type': 'str'},
    }

    def __init__(self, allow_text_entry=None, choices=None, display_as=None):
        super(MicrosoftgraphchoiceColumn, self).__init__()
        self.allow_text_entry = allow_text_entry
        self.choices = choices
        self.display_as = display_as
