# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphactivityHistoryItem(Model):
    """MicrosoftgraphactivityHistoryItem.

    :param id:
    :type id: str
    :param status: Possible values include: 'active', 'updated', 'deleted',
     'ignored', 'unknownFutureValue'
    :type status: str or ~users.models.enum
    :param active_duration_seconds:
    :type active_duration_seconds: int
    :param created_date_time:
    :type created_date_time: datetime
    :param last_active_date_time:
    :type last_active_date_time: datetime
    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    :param expiration_date_time:
    :type expiration_date_time: datetime
    :param started_date_time:
    :type started_date_time: datetime
    :param user_timezone:
    :type user_timezone: str
    :param activity:
    :type activity: ~users.models.MicrosoftgraphuserActivity
    """

    _validation = {
        'active_duration_seconds': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'active_duration_seconds': {'key': 'activeDurationSeconds', 'type': 'int'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'last_active_date_time': {'key': 'lastActiveDateTime', 'type': 'iso-8601'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'expiration_date_time': {'key': 'expirationDateTime', 'type': 'iso-8601'},
        'started_date_time': {'key': 'startedDateTime', 'type': 'iso-8601'},
        'user_timezone': {'key': 'userTimezone', 'type': 'str'},
        'activity': {'key': 'activity', 'type': 'MicrosoftgraphuserActivity'},
    }

    def __init__(self, id=None, status=None, active_duration_seconds=None, created_date_time=None, last_active_date_time=None, last_modified_date_time=None, expiration_date_time=None, started_date_time=None, user_timezone=None, activity=None):
        super(MicrosoftgraphactivityHistoryItem, self).__init__()
        self.id = id
        self.status = status
        self.active_duration_seconds = active_duration_seconds
        self.created_date_time = created_date_time
        self.last_active_date_time = last_active_date_time
        self.last_modified_date_time = last_modified_date_time
        self.expiration_date_time = expiration_date_time
        self.started_date_time = started_date_time
        self.user_timezone = user_timezone
        self.activity = activity
