# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdirectorySetting(Model):
    """MicrosoftgraphdirectorySetting.

    :param id:
    :type id: str
    :param display_name:
    :type display_name: str
    :param template_id:
    :type template_id: str
    :param values:
    :type values: list[~users.models.MicrosoftgraphsettingValue]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'template_id': {'key': 'templateId', 'type': 'str'},
        'values': {'key': 'values', 'type': '[MicrosoftgraphsettingValue]'},
    }

    def __init__(self, id=None, display_name=None, template_id=None, values=None):
        super(MicrosoftgraphdirectorySetting, self).__init__()
        self.id = id
        self.display_name = display_name
        self.template_id = template_id
        self.values = values
