# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphresourceReference(Model):
    """resourceReference.

    :param web_url:
    :type web_url: str
    :param id:
    :type id: str
    :param type:
    :type type: str
    """

    _attribute_map = {
        'web_url': {'key': 'webUrl', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, web_url=None, id=None, type=None):
        super(MicrosoftgraphresourceReference, self).__init__()
        self.web_url = web_url
        self.id = id
        self.type = type
