# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdriveItem(Model):
    """MicrosoftgraphdriveItem.

    :param id:
    :type id: str
    :param created_by:
    :type created_by: ~users.models.MicrosoftgraphidentitySet
    :param created_date_time:
    :type created_date_time: datetime
    :param description:
    :type description: str
    :param e_tag:
    :type e_tag: str
    :param last_modified_by:
    :type last_modified_by: ~users.models.MicrosoftgraphidentitySet
    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    :param name:
    :type name: str
    :param parent_reference:
    :type parent_reference: ~users.models.MicrosoftgraphitemReference
    :param web_url:
    :type web_url: str
    :param created_by_user:
    :type created_by_user: ~users.models.Microsoftgraphuser
    :param last_modified_by_user:
    :type last_modified_by_user: ~users.models.Microsoftgraphuser
    :param audio:
    :type audio: ~users.models.Microsoftgraphaudio
    :param bundle:
    :type bundle: ~users.models.Microsoftgraphbundle
    :param content:
    :type content: bytes
    :param c_tag:
    :type c_tag: str
    :param deleted:
    :type deleted: ~users.models.Microsoftgraphdeleted
    :param file:
    :type file: ~users.models.Microsoftgraphfile
    :param file_system_info:
    :type file_system_info: ~users.models.MicrosoftgraphfileSystemInfo
    :param folder:
    :type folder: ~users.models.Microsoftgraphfolder
    :param image:
    :type image: ~users.models.Microsoftgraphimage
    :param location:
    :type location: ~users.models.MicrosoftgraphgeoCoordinates
    :param package:
    :type package: ~users.models.Microsoftgraphpackage
    :param pending_operations:
    :type pending_operations: ~users.models.MicrosoftgraphpendingOperations
    :param photo:
    :type photo: ~users.models.Microsoftgraphphoto
    :param publication:
    :type publication: ~users.models.MicrosoftgraphpublicationFacet
    :param remote_item:
    :type remote_item: ~users.models.MicrosoftgraphremoteItem
    :param root:
    :type root: object
    :param search_result:
    :type search_result: ~users.models.MicrosoftgraphsearchResult
    :param shared:
    :type shared: ~users.models.Microsoftgraphshared
    :param sharepoint_ids:
    :type sharepoint_ids: ~users.models.MicrosoftgraphsharepointIds
    :param size:
    :type size: long
    :param special_folder:
    :type special_folder: ~users.models.MicrosoftgraphspecialFolder
    :param video:
    :type video: ~users.models.Microsoftgraphvideo
    :param web_dav_url:
    :type web_dav_url: str
    :param workbook:
    :type workbook: ~users.models.Microsoftgraphworkbook
    :param activities:
    :type activities: list[~users.models.MicrosoftgraphitemActivityOLD]
    :param analytics:
    :type analytics: ~users.models.MicrosoftgraphitemAnalytics
    :param children:
    :type children: list[~users.models.MicrosoftgraphdriveItem]
    :param list_item:
    :type list_item: ~users.models.MicrosoftgraphlistItem
    :param permissions:
    :type permissions: list[~users.models.Microsoftgraphpermission]
    :param subscriptions:
    :type subscriptions: list[~users.models.Microsoftgraphsubscription]
    :param thumbnails:
    :type thumbnails: list[~users.models.MicrosoftgraphthumbnailSet]
    :param versions:
    :type versions: list[~users.models.MicrosoftgraphdriveItemVersion]
    :param document:
    :type document: ~users.models.Microsoftgraphdocument
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'created_by': {'key': 'createdBy', 'type': 'MicrosoftgraphidentitySet'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'description': {'key': 'description', 'type': 'str'},
        'e_tag': {'key': 'eTag', 'type': 'str'},
        'last_modified_by': {'key': 'lastModifiedBy', 'type': 'MicrosoftgraphidentitySet'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'name': {'key': 'name', 'type': 'str'},
        'parent_reference': {'key': 'parentReference', 'type': 'MicrosoftgraphitemReference'},
        'web_url': {'key': 'webUrl', 'type': 'str'},
        'created_by_user': {'key': 'createdByUser', 'type': 'Microsoftgraphuser'},
        'last_modified_by_user': {'key': 'lastModifiedByUser', 'type': 'Microsoftgraphuser'},
        'audio': {'key': 'audio', 'type': 'Microsoftgraphaudio'},
        'bundle': {'key': 'bundle', 'type': 'Microsoftgraphbundle'},
        'content': {'key': 'content', 'type': 'base64'},
        'c_tag': {'key': 'cTag', 'type': 'str'},
        'deleted': {'key': 'deleted', 'type': 'Microsoftgraphdeleted'},
        'file': {'key': 'file', 'type': 'Microsoftgraphfile'},
        'file_system_info': {'key': 'fileSystemInfo', 'type': 'MicrosoftgraphfileSystemInfo'},
        'folder': {'key': 'folder', 'type': 'Microsoftgraphfolder'},
        'image': {'key': 'image', 'type': 'Microsoftgraphimage'},
        'location': {'key': 'location', 'type': 'MicrosoftgraphgeoCoordinates'},
        'package': {'key': 'package', 'type': 'Microsoftgraphpackage'},
        'pending_operations': {'key': 'pendingOperations', 'type': 'MicrosoftgraphpendingOperations'},
        'photo': {'key': 'photo', 'type': 'Microsoftgraphphoto'},
        'publication': {'key': 'publication', 'type': 'MicrosoftgraphpublicationFacet'},
        'remote_item': {'key': 'remoteItem', 'type': 'MicrosoftgraphremoteItem'},
        'root': {'key': 'root', 'type': 'object'},
        'search_result': {'key': 'searchResult', 'type': 'MicrosoftgraphsearchResult'},
        'shared': {'key': 'shared', 'type': 'Microsoftgraphshared'},
        'sharepoint_ids': {'key': 'sharepointIds', 'type': 'MicrosoftgraphsharepointIds'},
        'size': {'key': 'size', 'type': 'long'},
        'special_folder': {'key': 'specialFolder', 'type': 'MicrosoftgraphspecialFolder'},
        'video': {'key': 'video', 'type': 'Microsoftgraphvideo'},
        'web_dav_url': {'key': 'webDavUrl', 'type': 'str'},
        'workbook': {'key': 'workbook', 'type': 'Microsoftgraphworkbook'},
        'activities': {'key': 'activities', 'type': '[MicrosoftgraphitemActivityOLD]'},
        'analytics': {'key': 'analytics', 'type': 'MicrosoftgraphitemAnalytics'},
        'children': {'key': 'children', 'type': '[MicrosoftgraphdriveItem]'},
        'list_item': {'key': 'listItem', 'type': 'MicrosoftgraphlistItem'},
        'permissions': {'key': 'permissions', 'type': '[Microsoftgraphpermission]'},
        'subscriptions': {'key': 'subscriptions', 'type': '[Microsoftgraphsubscription]'},
        'thumbnails': {'key': 'thumbnails', 'type': '[MicrosoftgraphthumbnailSet]'},
        'versions': {'key': 'versions', 'type': '[MicrosoftgraphdriveItemVersion]'},
        'document': {'key': 'document', 'type': 'Microsoftgraphdocument'},
    }

    def __init__(self, id=None, created_by=None, created_date_time=None, description=None, e_tag=None, last_modified_by=None, last_modified_date_time=None, name=None, parent_reference=None, web_url=None, created_by_user=None, last_modified_by_user=None, audio=None, bundle=None, content=None, c_tag=None, deleted=None, file=None, file_system_info=None, folder=None, image=None, location=None, package=None, pending_operations=None, photo=None, publication=None, remote_item=None, root=None, search_result=None, shared=None, sharepoint_ids=None, size=None, special_folder=None, video=None, web_dav_url=None, workbook=None, activities=None, analytics=None, children=None, list_item=None, permissions=None, subscriptions=None, thumbnails=None, versions=None, document=None):
        super(MicrosoftgraphdriveItem, self).__init__()
        self.id = id
        self.created_by = created_by
        self.created_date_time = created_date_time
        self.description = description
        self.e_tag = e_tag
        self.last_modified_by = last_modified_by
        self.last_modified_date_time = last_modified_date_time
        self.name = name
        self.parent_reference = parent_reference
        self.web_url = web_url
        self.created_by_user = created_by_user
        self.last_modified_by_user = last_modified_by_user
        self.audio = audio
        self.bundle = bundle
        self.content = content
        self.c_tag = c_tag
        self.deleted = deleted
        self.file = file
        self.file_system_info = file_system_info
        self.folder = folder
        self.image = image
        self.location = location
        self.package = package
        self.pending_operations = pending_operations
        self.photo = photo
        self.publication = publication
        self.remote_item = remote_item
        self.root = root
        self.search_result = search_result
        self.shared = shared
        self.sharepoint_ids = sharepoint_ids
        self.size = size
        self.special_folder = special_folder
        self.video = video
        self.web_dav_url = web_dav_url
        self.workbook = workbook
        self.activities = activities
        self.analytics = analytics
        self.children = children
        self.list_item = list_item
        self.permissions = permissions
        self.subscriptions = subscriptions
        self.thumbnails = thumbnails
        self.versions = versions
        self.document = document
