# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Microsoftgraphpermission(Model):
    """Microsoftgraphpermission.

    :param id:
    :type id: str
    :param expiration_date_time:
    :type expiration_date_time: datetime
    :param granted_to:
    :type granted_to: ~users.models.MicrosoftgraphidentitySet
    :param granted_to_identities:
    :type granted_to_identities: list[~users.models.MicrosoftgraphidentitySet]
    :param has_password:
    :type has_password: bool
    :param inherited_from:
    :type inherited_from: ~users.models.MicrosoftgraphitemReference
    :param invitation:
    :type invitation: ~users.models.MicrosoftgraphsharingInvitation
    :param link:
    :type link: ~users.models.MicrosoftgraphsharingLink
    :param roles:
    :type roles: list[str]
    :param share_id:
    :type share_id: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'expiration_date_time': {'key': 'expirationDateTime', 'type': 'iso-8601'},
        'granted_to': {'key': 'grantedTo', 'type': 'MicrosoftgraphidentitySet'},
        'granted_to_identities': {'key': 'grantedToIdentities', 'type': '[MicrosoftgraphidentitySet]'},
        'has_password': {'key': 'hasPassword', 'type': 'bool'},
        'inherited_from': {'key': 'inheritedFrom', 'type': 'MicrosoftgraphitemReference'},
        'invitation': {'key': 'invitation', 'type': 'MicrosoftgraphsharingInvitation'},
        'link': {'key': 'link', 'type': 'MicrosoftgraphsharingLink'},
        'roles': {'key': 'roles', 'type': '[str]'},
        'share_id': {'key': 'shareId', 'type': 'str'},
    }

    def __init__(self, id=None, expiration_date_time=None, granted_to=None, granted_to_identities=None, has_password=None, inherited_from=None, invitation=None, link=None, roles=None, share_id=None):
        super(Microsoftgraphpermission, self).__init__()
        self.id = id
        self.expiration_date_time = expiration_date_time
        self.granted_to = granted_to
        self.granted_to_identities = granted_to_identities
        self.has_password = has_password
        self.inherited_from = inherited_from
        self.invitation = invitation
        self.link = link
        self.roles = roles
        self.share_id = share_id
