# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphtimeSlot(Model):
    """timeSlot.

    :param start:
    :type start: ~users.models.MicrosoftgraphdateTimeTimeZone
    :param end:
    :type end: ~users.models.MicrosoftgraphdateTimeTimeZone
    """

    _attribute_map = {
        'start': {'key': 'start', 'type': 'MicrosoftgraphdateTimeTimeZone'},
        'end': {'key': 'end', 'type': 'MicrosoftgraphdateTimeTimeZone'},
    }

    def __init__(self, start=None, end=None):
        super(MicrosoftgraphtimeSlot, self).__init__()
        self.start = start
        self.end = end
