# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphresponseStatus(Model):
    """responseStatus.

    :param response: Possible values include: 'none', 'organizer',
     'tentativelyAccepted', 'accepted', 'declined', 'notResponded'
    :type response: str or ~users.models.enum
    :param time:
    :type time: datetime
    """

    _attribute_map = {
        'response': {'key': 'response', 'type': 'str'},
        'time': {'key': 'time', 'type': 'iso-8601'},
    }

    def __init__(self, response=None, time=None):
        super(MicrosoftgraphresponseStatus, self).__init__()
        self.response = response
        self.time = time
