# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphassignedLabel(Model):
    """assignedLabel.

    :param label_id:
    :type label_id: str
    :param display_name:
    :type display_name: str
    """

    _attribute_map = {
        'label_id': {'key': 'labelId', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
    }

    def __init__(self, label_id=None, display_name=None):
        super(MicrosoftgraphassignedLabel, self).__init__()
        self.label_id = label_id
        self.display_name = display_name
