# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookTableSort(Model):
    """MicrosoftgraphworkbookTableSort.

    :param id:
    :type id: str
    :param fields:
    :type fields: list[~users.models.MicrosoftgraphworkbookSortField]
    :param match_case:
    :type match_case: bool
    :param method:
    :type method: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'fields': {'key': 'fields', 'type': '[MicrosoftgraphworkbookSortField]'},
        'match_case': {'key': 'matchCase', 'type': 'bool'},
        'method': {'key': 'method', 'type': 'str'},
    }

    def __init__(self, id=None, fields=None, match_case=None, method=None):
        super(MicrosoftgraphworkbookTableSort, self).__init__()
        self.id = id
        self.fields = fields
        self.match_case = match_case
        self.method = method
