# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphinferenceClassificationOverride(Model):
    """MicrosoftgraphinferenceClassificationOverride.

    :param id:
    :type id: str
    :param classify_as: Possible values include: 'focused', 'other'
    :type classify_as: str or ~users.models.enum
    :param sender_email_address:
    :type sender_email_address: ~users.models.MicrosoftgraphemailAddress
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'classify_as': {'key': 'classifyAs', 'type': 'str'},
        'sender_email_address': {'key': 'senderEmailAddress', 'type': 'MicrosoftgraphemailAddress'},
    }

    def __init__(self, id=None, classify_as=None, sender_email_address=None):
        super(MicrosoftgraphinferenceClassificationOverride, self).__init__()
        self.id = id
        self.classify_as = classify_as
        self.sender_email_address = sender_email_address
