# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphteamsCatalogApp(Model):
    """MicrosoftgraphteamsCatalogApp.

    :param id:
    :type id: str
    :param external_id:
    :type external_id: str
    :param name:
    :type name: str
    :param version:
    :type version: str
    :param distribution_method: Possible values include: 'store',
     'organization', 'sideloaded', 'unknownFutureValue'
    :type distribution_method: str or ~users.models.enum
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'external_id': {'key': 'externalId', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'distribution_method': {'key': 'distributionMethod', 'type': 'str'},
    }

    def __init__(self, id=None, external_id=None, name=None, version=None, distribution_method=None):
        super(MicrosoftgraphteamsCatalogApp, self).__init__()
        self.id = id
        self.external_id = external_id
        self.name = name
        self.version = version
        self.distribution_method = distribution_method
