# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphuserConfiguration(Model):
    """MicrosoftgraphuserConfiguration.

    :param id:
    :type id: str
    :param binary_data:
    :type binary_data: bytes
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'binary_data': {'key': 'binaryData', 'type': 'base64'},
    }

    def __init__(self, id=None, binary_data=None):
        super(MicrosoftgraphuserConfiguration, self).__init__()
        self.id = id
        self.binary_data = binary_data
