# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphplannerBucket(Model):
    """MicrosoftgraphplannerBucket.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param plan_id:
    :type plan_id: str
    :param order_hint:
    :type order_hint: str
    :param tasks:
    :type tasks: list[~users.models.MicrosoftgraphplannerTask]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'plan_id': {'key': 'planId', 'type': 'str'},
        'order_hint': {'key': 'orderHint', 'type': 'str'},
        'tasks': {'key': 'tasks', 'type': '[MicrosoftgraphplannerTask]'},
    }

    def __init__(self, id=None, name=None, plan_id=None, order_hint=None, tasks=None):
        super(MicrosoftgraphplannerBucket, self).__init__()
        self.id = id
        self.name = name
        self.plan_id = plan_id
        self.order_hint = order_hint
        self.tasks = tasks
