# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdeleteAction(Model):
    """deleteAction.

    :param name:
    :type name: str
    :param object_type:
    :type object_type: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'object_type': {'key': 'objectType', 'type': 'str'},
    }

    def __init__(self, name=None, object_type=None):
        super(MicrosoftgraphdeleteAction, self).__init__()
        self.name = name
        self.object_type = object_type
