# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphemailAddress(Model):
    """emailAddress.

    :param name:
    :type name: str
    :param address:
    :type address: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'address': {'key': 'address', 'type': 'str'},
    }

    def __init__(self, name=None, address=None):
        super(MicrosoftgraphemailAddress, self).__init__()
        self.name = name
        self.address = address
