# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdateTimeTimeZone(Model):
    """dateTimeTimeZone.

    :param date_time_property:
    :type date_time_property: str
    :param time_zone:
    :type time_zone: str
    """

    _attribute_map = {
        'date_time_property': {'key': 'dateTime', 'type': 'str'},
        'time_zone': {'key': 'timeZone', 'type': 'str'},
    }

    def __init__(self, date_time_property=None, time_zone=None):
        super(MicrosoftgraphdateTimeTimeZone, self).__init__()
        self.date_time_property = date_time_property
        self.time_zone = time_zone
