# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphmobileAppTroubleshootingEvent(Model):
    """MicrosoftgraphmobileAppTroubleshootingEvent.

    :param id:
    :type id: str
    :param event_date_time: Time when the event occurred .
    :type event_date_time: datetime
    :param correlation_id: Id used for tracing the failure in the service.
    :type correlation_id: str
    :param troubleshooting_error_details:
    :type troubleshooting_error_details:
     ~users.models.MicrosoftgraphdeviceManagementTroubleshootingErrorDetails
    :param event_name: Event Name corresponding to the Troubleshooting Event.
     It is an Optional field
    :type event_name: str
    :param additional_information: A set of string key and string value pairs
     which provides additional information on the Troubleshooting event
    :type additional_information:
     list[~users.models.MicrosoftgraphkeyValuePair]
    :param managed_device_identifier: Device identifier created or collected
     by Intune.
    :type managed_device_identifier: str
    :param user_id: Identifier for the user that tried to enroll the device.
    :type user_id: str
    :param application_id: Intune application identifier.
    :type application_id: str
    :param history: Intune Mobile Application Troubleshooting History Item
    :type history:
     list[~users.models.MicrosoftgraphmobileAppTroubleshootingHistoryItem]
    :param app_log_collection_requests:
    :type app_log_collection_requests:
     list[~users.models.MicrosoftgraphappLogCollectionRequest]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'event_date_time': {'key': 'eventDateTime', 'type': 'iso-8601'},
        'correlation_id': {'key': 'correlationId', 'type': 'str'},
        'troubleshooting_error_details': {'key': 'troubleshootingErrorDetails', 'type': 'MicrosoftgraphdeviceManagementTroubleshootingErrorDetails'},
        'event_name': {'key': 'eventName', 'type': 'str'},
        'additional_information': {'key': 'additionalInformation', 'type': '[MicrosoftgraphkeyValuePair]'},
        'managed_device_identifier': {'key': 'managedDeviceIdentifier', 'type': 'str'},
        'user_id': {'key': 'userId', 'type': 'str'},
        'application_id': {'key': 'applicationId', 'type': 'str'},
        'history': {'key': 'history', 'type': '[MicrosoftgraphmobileAppTroubleshootingHistoryItem]'},
        'app_log_collection_requests': {'key': 'appLogCollectionRequests', 'type': '[MicrosoftgraphappLogCollectionRequest]'},
    }

    def __init__(self, id=None, event_date_time=None, correlation_id=None, troubleshooting_error_details=None, event_name=None, additional_information=None, managed_device_identifier=None, user_id=None, application_id=None, history=None, app_log_collection_requests=None):
        super(MicrosoftgraphmobileAppTroubleshootingEvent, self).__init__()
        self.id = id
        self.event_date_time = event_date_time
        self.correlation_id = correlation_id
        self.troubleshooting_error_details = troubleshooting_error_details
        self.event_name = event_name
        self.additional_information = additional_information
        self.managed_device_identifier = managed_device_identifier
        self.user_id = user_id
        self.application_id = application_id
        self.history = history
        self.app_log_collection_requests = app_log_collection_requests
