# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphtimeOffRequest(Model):
    """MicrosoftgraphtimeOffRequest.

    :param id:
    :type id: str
    :param created_date_time:
    :type created_date_time: datetime
    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    :param last_modified_by:
    :type last_modified_by: ~users.models.MicrosoftgraphidentitySet
    :param assigned_to: Possible values include: 'sender', 'recipient',
     'manager', 'system', 'unknownFutureValue'
    :type assigned_to: str or ~users.models.enum
    :param state: Possible values include: 'pending', 'approved', 'declined',
     'unknownFutureValue'
    :type state: str or ~users.models.enum
    :param sender_message:
    :type sender_message: str
    :param sender_date_time:
    :type sender_date_time: datetime
    :param manager_action_message:
    :type manager_action_message: str
    :param manager_action_date_time:
    :type manager_action_date_time: datetime
    :param sender_user_id:
    :type sender_user_id: str
    :param manager_user_id:
    :type manager_user_id: str
    :param start_date_time:
    :type start_date_time: datetime
    :param end_date_time:
    :type end_date_time: datetime
    :param time_off_reason_id:
    :type time_off_reason_id: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'last_modified_by': {'key': 'lastModifiedBy', 'type': 'MicrosoftgraphidentitySet'},
        'assigned_to': {'key': 'assignedTo', 'type': 'str'},
        'state': {'key': 'state', 'type': 'str'},
        'sender_message': {'key': 'senderMessage', 'type': 'str'},
        'sender_date_time': {'key': 'senderDateTime', 'type': 'iso-8601'},
        'manager_action_message': {'key': 'managerActionMessage', 'type': 'str'},
        'manager_action_date_time': {'key': 'managerActionDateTime', 'type': 'iso-8601'},
        'sender_user_id': {'key': 'senderUserId', 'type': 'str'},
        'manager_user_id': {'key': 'managerUserId', 'type': 'str'},
        'start_date_time': {'key': 'startDateTime', 'type': 'iso-8601'},
        'end_date_time': {'key': 'endDateTime', 'type': 'iso-8601'},
        'time_off_reason_id': {'key': 'timeOffReasonId', 'type': 'str'},
    }

    def __init__(self, id=None, created_date_time=None, last_modified_date_time=None, last_modified_by=None, assigned_to=None, state=None, sender_message=None, sender_date_time=None, manager_action_message=None, manager_action_date_time=None, sender_user_id=None, manager_user_id=None, start_date_time=None, end_date_time=None, time_off_reason_id=None):
        super(MicrosoftgraphtimeOffRequest, self).__init__()
        self.id = id
        self.created_date_time = created_date_time
        self.last_modified_date_time = last_modified_date_time
        self.last_modified_by = last_modified_by
        self.assigned_to = assigned_to
        self.state = state
        self.sender_message = sender_message
        self.sender_date_time = sender_date_time
        self.manager_action_message = manager_action_message
        self.manager_action_date_time = manager_action_date_time
        self.sender_user_id = sender_user_id
        self.manager_user_id = manager_user_id
        self.start_date_time = start_date_time
        self.end_date_time = end_date_time
        self.time_off_reason_id = time_off_reason_id
