# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphteamMessagingSettings(Model):
    """teamMessagingSettings.

    :param allow_user_edit_messages:
    :type allow_user_edit_messages: bool
    :param allow_user_delete_messages:
    :type allow_user_delete_messages: bool
    :param allow_owner_delete_messages:
    :type allow_owner_delete_messages: bool
    :param allow_team_mentions:
    :type allow_team_mentions: bool
    :param allow_channel_mentions:
    :type allow_channel_mentions: bool
    """

    _attribute_map = {
        'allow_user_edit_messages': {'key': 'allowUserEditMessages', 'type': 'bool'},
        'allow_user_delete_messages': {'key': 'allowUserDeleteMessages', 'type': 'bool'},
        'allow_owner_delete_messages': {'key': 'allowOwnerDeleteMessages', 'type': 'bool'},
        'allow_team_mentions': {'key': 'allowTeamMentions', 'type': 'bool'},
        'allow_channel_mentions': {'key': 'allowChannelMentions', 'type': 'bool'},
    }

    def __init__(self, allow_user_edit_messages=None, allow_user_delete_messages=None, allow_owner_delete_messages=None, allow_team_mentions=None, allow_channel_mentions=None):
        super(MicrosoftgraphteamMessagingSettings, self).__init__()
        self.allow_user_edit_messages = allow_user_edit_messages
        self.allow_user_delete_messages = allow_user_delete_messages
        self.allow_owner_delete_messages = allow_owner_delete_messages
        self.allow_team_mentions = allow_team_mentions
        self.allow_channel_mentions = allow_channel_mentions
