# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Microsoftgraphphone(Model):
    """phone.

    :param type: Possible values include: 'home', 'business', 'mobile',
     'other', 'assistant', 'homeFax', 'businessFax', 'otherFax', 'pager',
     'radio'
    :type type: str or ~users.models.enum
    :param number:
    :type number: str
    """

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'number': {'key': 'number', 'type': 'str'},
    }

    def __init__(self, type=None, number=None):
        super(Microsoftgraphphone, self).__init__()
        self.type = type
        self.number = number
