# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphuserTeamwork(Model):
    """MicrosoftgraphuserTeamwork.

    :param id:
    :type id: str
    :param installed_apps:
    :type installed_apps:
     list[~users.models.MicrosoftgraphteamsAppInstallation]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'installed_apps': {'key': 'installedApps', 'type': '[MicrosoftgraphteamsAppInstallation]'},
    }

    def __init__(self, id=None, installed_apps=None):
        super(MicrosoftgraphuserTeamwork, self).__init__()
        self.id = id
        self.installed_apps = installed_apps
