# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphrecurrenceRange(Model):
    """recurrenceRange.

    :param type: Possible values include: 'endDate', 'noEnd', 'numbered'
    :type type: str or ~users.models.enum
    :param start_date:
    :type start_date: date
    :param end_date:
    :type end_date: date
    :param recurrence_time_zone:
    :type recurrence_time_zone: str
    :param number_of_occurrences:
    :type number_of_occurrences: int
    """

    _validation = {
        'number_of_occurrences': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'start_date': {'key': 'startDate', 'type': 'date'},
        'end_date': {'key': 'endDate', 'type': 'date'},
        'recurrence_time_zone': {'key': 'recurrenceTimeZone', 'type': 'str'},
        'number_of_occurrences': {'key': 'numberOfOccurrences', 'type': 'int'},
    }

    def __init__(self, type=None, start_date=None, end_date=None, recurrence_time_zone=None, number_of_occurrences=None):
        super(MicrosoftgraphrecurrenceRange, self).__init__()
        self.type = type
        self.start_date = start_date
        self.end_date = end_date
        self.recurrence_time_zone = recurrence_time_zone
        self.number_of_occurrences = number_of_occurrences
