# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphinsightIdentity(Model):
    """insightIdentity.

    :param display_name:
    :type display_name: str
    :param id:
    :type id: str
    :param address:
    :type address: str
    """

    _attribute_map = {
        'display_name': {'key': 'displayName', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'address': {'key': 'address', 'type': 'str'},
    }

    def __init__(self, display_name=None, id=None, address=None):
        super(MicrosoftgraphinsightIdentity, self).__init__()
        self.display_name = display_name
        self.id = id
        self.address = address
