# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Microsoftgraphendpoint(Model):
    """Microsoftgraphendpoint.

    :param id:
    :type id: str
    :param deleted_date_time:
    :type deleted_date_time: datetime
    :param capability:
    :type capability: str
    :param provider_id:
    :type provider_id: str
    :param provider_name:
    :type provider_name: str
    :param uri:
    :type uri: str
    :param provider_resource_id:
    :type provider_resource_id: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'deleted_date_time': {'key': 'deletedDateTime', 'type': 'iso-8601'},
        'capability': {'key': 'capability', 'type': 'str'},
        'provider_id': {'key': 'providerId', 'type': 'str'},
        'provider_name': {'key': 'providerName', 'type': 'str'},
        'uri': {'key': 'uri', 'type': 'str'},
        'provider_resource_id': {'key': 'providerResourceId', 'type': 'str'},
    }

    def __init__(self, id=None, deleted_date_time=None, capability=None, provider_id=None, provider_name=None, uri=None, provider_resource_id=None):
        super(Microsoftgraphendpoint, self).__init__()
        self.id = id
        self.deleted_date_time = deleted_date_time
        self.capability = capability
        self.provider_id = provider_id
        self.provider_name = provider_name
        self.uri = uri
        self.provider_resource_id = provider_resource_id
