# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookFilterCriteria(Model):
    """workbookFilterCriteria.

    :param color:
    :type color: str
    :param criterion1:
    :type criterion1: str
    :param criterion2:
    :type criterion2: str
    :param dynamic_criteria:
    :type dynamic_criteria: str
    :param filter_on:
    :type filter_on: str
    :param icon:
    :type icon: ~users.models.MicrosoftgraphworkbookIcon
    :param operator:
    :type operator: str
    :param values:
    :type values: object
    """

    _attribute_map = {
        'color': {'key': 'color', 'type': 'str'},
        'criterion1': {'key': 'criterion1', 'type': 'str'},
        'criterion2': {'key': 'criterion2', 'type': 'str'},
        'dynamic_criteria': {'key': 'dynamicCriteria', 'type': 'str'},
        'filter_on': {'key': 'filterOn', 'type': 'str'},
        'icon': {'key': 'icon', 'type': 'MicrosoftgraphworkbookIcon'},
        'operator': {'key': 'operator', 'type': 'str'},
        'values': {'key': 'values', 'type': 'object'},
    }

    def __init__(self, color=None, criterion1=None, criterion2=None, dynamic_criteria=None, filter_on=None, icon=None, operator=None, values=None):
        super(MicrosoftgraphworkbookFilterCriteria, self).__init__()
        self.color = color
        self.criterion1 = criterion1
        self.criterion2 = criterion2
        self.dynamic_criteria = dynamic_criteria
        self.filter_on = filter_on
        self.icon = icon
        self.operator = operator
        self.values = values
