# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphlicenseAssignmentState(Model):
    """licenseAssignmentState.

    :param sku_id:
    :type sku_id: str
    :param disabled_plans:
    :type disabled_plans: list[str]
    :param assigned_by_group:
    :type assigned_by_group: str
    :param state:
    :type state: str
    :param error:
    :type error: str
    """

    _attribute_map = {
        'sku_id': {'key': 'skuId', 'type': 'str'},
        'disabled_plans': {'key': 'disabledPlans', 'type': '[str]'},
        'assigned_by_group': {'key': 'assignedByGroup', 'type': 'str'},
        'state': {'key': 'state', 'type': 'str'},
        'error': {'key': 'error', 'type': 'str'},
    }

    def __init__(self, sku_id=None, disabled_plans=None, assigned_by_group=None, state=None, error=None):
        super(MicrosoftgraphlicenseAssignmentState, self).__init__()
        self.sku_id = sku_id
        self.disabled_plans = disabled_plans
        self.assigned_by_group = assigned_by_group
        self.state = state
        self.error = error
