# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphpersonOrGroupColumn(Model):
    """personOrGroupColumn.

    :param allow_multiple_selection:
    :type allow_multiple_selection: bool
    :param choose_from_type:
    :type choose_from_type: str
    :param display_as:
    :type display_as: str
    """

    _attribute_map = {
        'allow_multiple_selection': {'key': 'allowMultipleSelection', 'type': 'bool'},
        'choose_from_type': {'key': 'chooseFromType', 'type': 'str'},
        'display_as': {'key': 'displayAs', 'type': 'str'},
    }

    def __init__(self, allow_multiple_selection=None, choose_from_type=None, display_as=None):
        super(MicrosoftgraphpersonOrGroupColumn, self).__init__()
        self.allow_multiple_selection = allow_multiple_selection
        self.choose_from_type = choose_from_type
        self.display_as = display_as
