# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphrenameAction(Model):
    """renameAction.

    :param new_name:
    :type new_name: str
    :param old_name:
    :type old_name: str
    """

    _attribute_map = {
        'new_name': {'key': 'newName', 'type': 'str'},
        'old_name': {'key': 'oldName', 'type': 'str'},
    }

    def __init__(self, new_name=None, old_name=None):
        super(MicrosoftgraphrenameAction, self).__init__()
        self.new_name = new_name
        self.old_name = old_name
