# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphonlineMeeting(Model):
    """MicrosoftgraphonlineMeeting.

    :param id:
    :type id: str
    :param creation_date_time:
    :type creation_date_time: datetime
    :param start_date_time:
    :type start_date_time: datetime
    :param end_date_time:
    :type end_date_time: datetime
    :param canceled_date_time:
    :type canceled_date_time: datetime
    :param expiration_date_time:
    :type expiration_date_time: datetime
    :param entry_exit_announcement:
    :type entry_exit_announcement: bool
    :param join_url:
    :type join_url: str
    :param subject:
    :type subject: str
    :param is_cancelled:
    :type is_cancelled: bool
    :param participants:
    :type participants: ~users.models.MicrosoftgraphmeetingParticipants
    :param is_broadcast:
    :type is_broadcast: bool
    :param access_level: Possible values include: 'everyone', 'invited',
     'locked', 'sameEnterprise', 'sameEnterpriseAndFederated'
    :type access_level: str or ~users.models.enum
    :param capabilities:
    :type capabilities: list[str]
    :param audio_conferencing:
    :type audio_conferencing: ~users.models.MicrosoftgraphaudioConferencing
    :param chat_info:
    :type chat_info: ~users.models.MicrosoftgraphchatInfo
    :param video_teleconference_id:
    :type video_teleconference_id: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'creation_date_time': {'key': 'creationDateTime', 'type': 'iso-8601'},
        'start_date_time': {'key': 'startDateTime', 'type': 'iso-8601'},
        'end_date_time': {'key': 'endDateTime', 'type': 'iso-8601'},
        'canceled_date_time': {'key': 'canceledDateTime', 'type': 'iso-8601'},
        'expiration_date_time': {'key': 'expirationDateTime', 'type': 'iso-8601'},
        'entry_exit_announcement': {'key': 'entryExitAnnouncement', 'type': 'bool'},
        'join_url': {'key': 'joinUrl', 'type': 'str'},
        'subject': {'key': 'subject', 'type': 'str'},
        'is_cancelled': {'key': 'isCancelled', 'type': 'bool'},
        'participants': {'key': 'participants', 'type': 'MicrosoftgraphmeetingParticipants'},
        'is_broadcast': {'key': 'isBroadcast', 'type': 'bool'},
        'access_level': {'key': 'accessLevel', 'type': 'str'},
        'capabilities': {'key': 'capabilities', 'type': '[str]'},
        'audio_conferencing': {'key': 'audioConferencing', 'type': 'MicrosoftgraphaudioConferencing'},
        'chat_info': {'key': 'chatInfo', 'type': 'MicrosoftgraphchatInfo'},
        'video_teleconference_id': {'key': 'videoTeleconferenceId', 'type': 'str'},
    }

    def __init__(self, id=None, creation_date_time=None, start_date_time=None, end_date_time=None, canceled_date_time=None, expiration_date_time=None, entry_exit_announcement=None, join_url=None, subject=None, is_cancelled=None, participants=None, is_broadcast=None, access_level=None, capabilities=None, audio_conferencing=None, chat_info=None, video_teleconference_id=None):
        super(MicrosoftgraphonlineMeeting, self).__init__()
        self.id = id
        self.creation_date_time = creation_date_time
        self.start_date_time = start_date_time
        self.end_date_time = end_date_time
        self.canceled_date_time = canceled_date_time
        self.expiration_date_time = expiration_date_time
        self.entry_exit_announcement = entry_exit_announcement
        self.join_url = join_url
        self.subject = subject
        self.is_cancelled = is_cancelled
        self.participants = participants
        self.is_broadcast = is_broadcast
        self.access_level = access_level
        self.capabilities = capabilities
        self.audio_conferencing = audio_conferencing
        self.chat_info = chat_info
        self.video_teleconference_id = video_teleconference_id
