# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookWorksheetProtection(Model):
    """MicrosoftgraphworkbookWorksheetProtection.

    :param id:
    :type id: str
    :param options:
    :type options:
     ~users.models.MicrosoftgraphworkbookWorksheetProtectionOptions
    :param protected:
    :type protected: bool
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'options': {'key': 'options', 'type': 'MicrosoftgraphworkbookWorksheetProtectionOptions'},
        'protected': {'key': 'protected', 'type': 'bool'},
    }

    def __init__(self, id=None, options=None, protected=None):
        super(MicrosoftgraphworkbookWorksheetProtection, self).__init__()
        self.id = id
        self.options = options
        self.protected = protected
