# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphnumberColumn(Model):
    """numberColumn.

    :param decimal_places:
    :type decimal_places: str
    :param display_as:
    :type display_as: str
    :param maximum:
    :type maximum: float
    :param minimum:
    :type minimum: float
    """

    _attribute_map = {
        'decimal_places': {'key': 'decimalPlaces', 'type': 'str'},
        'display_as': {'key': 'displayAs', 'type': 'str'},
        'maximum': {'key': 'maximum', 'type': 'float'},
        'minimum': {'key': 'minimum', 'type': 'float'},
    }

    def __init__(self, decimal_places=None, display_as=None, maximum=None, minimum=None):
        super(MicrosoftgraphnumberColumn, self).__init__()
        self.decimal_places = decimal_places
        self.display_as = display_as
        self.maximum = maximum
        self.minimum = minimum
