# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphlookupColumn(Model):
    """lookupColumn.

    :param allow_multiple_values:
    :type allow_multiple_values: bool
    :param allow_unlimited_length:
    :type allow_unlimited_length: bool
    :param column_name:
    :type column_name: str
    :param list_id:
    :type list_id: str
    :param primary_lookup_column_id:
    :type primary_lookup_column_id: str
    """

    _attribute_map = {
        'allow_multiple_values': {'key': 'allowMultipleValues', 'type': 'bool'},
        'allow_unlimited_length': {'key': 'allowUnlimitedLength', 'type': 'bool'},
        'column_name': {'key': 'columnName', 'type': 'str'},
        'list_id': {'key': 'listId', 'type': 'str'},
        'primary_lookup_column_id': {'key': 'primaryLookupColumnId', 'type': 'str'},
    }

    def __init__(self, allow_multiple_values=None, allow_unlimited_length=None, column_name=None, list_id=None, primary_lookup_column_id=None):
        super(MicrosoftgraphlookupColumn, self).__init__()
        self.allow_multiple_values = allow_multiple_values
        self.allow_unlimited_length = allow_unlimited_length
        self.column_name = column_name
        self.list_id = list_id
        self.primary_lookup_column_id = primary_lookup_column_id
