# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphcompanyDetail(Model):
    """companyDetail.

    :param display_name:
    :type display_name: str
    :param pronunciation:
    :type pronunciation: str
    :param department:
    :type department: str
    :param office_location:
    :type office_location: str
    :param address:
    :type address: ~users.models.MicrosoftgraphphysicalAddress
    :param web_url:
    :type web_url: str
    """

    _attribute_map = {
        'display_name': {'key': 'displayName', 'type': 'str'},
        'pronunciation': {'key': 'pronunciation', 'type': 'str'},
        'department': {'key': 'department', 'type': 'str'},
        'office_location': {'key': 'officeLocation', 'type': 'str'},
        'address': {'key': 'address', 'type': 'MicrosoftgraphphysicalAddress'},
        'web_url': {'key': 'webUrl', 'type': 'str'},
    }

    def __init__(self, display_name=None, pronunciation=None, department=None, office_location=None, address=None, web_url=None):
        super(MicrosoftgraphcompanyDetail, self).__init__()
        self.display_name = display_name
        self.pronunciation = pronunciation
        self.department = department
        self.office_location = office_location
        self.address = address
        self.web_url = web_url
