# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookChartAxisTitleFormat(Model):
    """MicrosoftgraphworkbookChartAxisTitleFormat.

    :param id:
    :type id: str
    :param font:
    :type font: ~users.models.MicrosoftgraphworkbookChartFont
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'font': {'key': 'font', 'type': 'MicrosoftgraphworkbookChartFont'},
    }

    def __init__(self, id=None, font=None):
        super(MicrosoftgraphworkbookChartAxisTitleFormat, self).__init__()
        self.id = id
        self.font = font
