# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphinferenceClassification(Model):
    """MicrosoftgraphinferenceClassification.

    :param id:
    :type id: str
    :param overrides:
    :type overrides:
     list[~users.models.MicrosoftgraphinferenceClassificationOverride]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'overrides': {'key': 'overrides', 'type': '[MicrosoftgraphinferenceClassificationOverride]'},
    }

    def __init__(self, id=None, overrides=None):
        super(MicrosoftgraphinferenceClassification, self).__init__()
        self.id = id
        self.overrides = overrides
