# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphoutlookUser(Model):
    """MicrosoftgraphoutlookUser.

    :param id:
    :type id: str
    :param master_categories:
    :type master_categories: list[~users.models.MicrosoftgraphoutlookCategory]
    :param task_groups:
    :type task_groups: list[~users.models.MicrosoftgraphoutlookTaskGroup]
    :param task_folders:
    :type task_folders: list[~users.models.MicrosoftgraphoutlookTaskFolder]
    :param tasks:
    :type tasks: list[~users.models.MicrosoftgraphoutlookTask]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'master_categories': {'key': 'masterCategories', 'type': '[MicrosoftgraphoutlookCategory]'},
        'task_groups': {'key': 'taskGroups', 'type': '[MicrosoftgraphoutlookTaskGroup]'},
        'task_folders': {'key': 'taskFolders', 'type': '[MicrosoftgraphoutlookTaskFolder]'},
        'tasks': {'key': 'tasks', 'type': '[MicrosoftgraphoutlookTask]'},
    }

    def __init__(self, id=None, master_categories=None, task_groups=None, task_folders=None, tasks=None):
        super(MicrosoftgraphoutlookUser, self).__init__()
        self.id = id
        self.master_categories = master_categories
        self.task_groups = task_groups
        self.task_folders = task_folders
        self.tasks = tasks
