# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphsharedInsight(Model):
    """MicrosoftgraphsharedInsight.

    :param id:
    :type id: str
    :param last_shared:
    :type last_shared: ~users.models.MicrosoftgraphsharingDetail
    :param sharing_history:
    :type sharing_history: list[~users.models.MicrosoftgraphsharingDetail]
    :param resource_visualization:
    :type resource_visualization:
     ~users.models.MicrosoftgraphresourceVisualization
    :param resource_reference:
    :type resource_reference: ~users.models.MicrosoftgraphresourceReference
    :param last_shared_method:
    :type last_shared_method: ~users.models.Microsoftgraphentity
    :param resource:
    :type resource: ~users.models.Microsoftgraphentity
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'last_shared': {'key': 'lastShared', 'type': 'MicrosoftgraphsharingDetail'},
        'sharing_history': {'key': 'sharingHistory', 'type': '[MicrosoftgraphsharingDetail]'},
        'resource_visualization': {'key': 'resourceVisualization', 'type': 'MicrosoftgraphresourceVisualization'},
        'resource_reference': {'key': 'resourceReference', 'type': 'MicrosoftgraphresourceReference'},
        'last_shared_method': {'key': 'lastSharedMethod', 'type': 'Microsoftgraphentity'},
        'resource': {'key': 'resource', 'type': 'Microsoftgraphentity'},
    }

    def __init__(self, id=None, last_shared=None, sharing_history=None, resource_visualization=None, resource_reference=None, last_shared_method=None, resource=None):
        super(MicrosoftgraphsharedInsight, self).__init__()
        self.id = id
        self.last_shared = last_shared
        self.sharing_history = sharing_history
        self.resource_visualization = resource_visualization
        self.resource_reference = resource_reference
        self.last_shared_method = last_shared_method
        self.resource = resource
