# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphpatternedRecurrence(Model):
    """patternedRecurrence.

    :param pattern:
    :type pattern: ~users.models.MicrosoftgraphrecurrencePattern
    :param range:
    :type range: ~users.models.MicrosoftgraphrecurrenceRange
    """

    _attribute_map = {
        'pattern': {'key': 'pattern', 'type': 'MicrosoftgraphrecurrencePattern'},
        'range': {'key': 'range', 'type': 'MicrosoftgraphrecurrenceRange'},
    }

    def __init__(self, pattern=None, range=None):
        super(MicrosoftgraphpatternedRecurrence, self).__init__()
        self.pattern = pattern
        self.range = range
