# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphidentityUserRisk(Model):
    """identityUserRisk.

    :param level: Possible values include: 'unknown', 'none', 'low', 'medium',
     'high'
    :type level: str or ~users.models.enum
    :param last_changed_date_time:
    :type last_changed_date_time: datetime
    """

    _attribute_map = {
        'level': {'key': 'level', 'type': 'str'},
        'last_changed_date_time': {'key': 'lastChangedDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, level=None, last_changed_date_time=None):
        super(MicrosoftgraphidentityUserRisk, self).__init__()
        self.level = level
        self.last_changed_date_time = last_changed_date_time
