# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphidentitySet(Model):
    """identitySet.

    :param application:
    :type application: ~users.models.Microsoftgraphidentity
    :param device:
    :type device: ~users.models.Microsoftgraphidentity
    :param user:
    :type user: ~users.models.Microsoftgraphidentity
    """

    _attribute_map = {
        'application': {'key': 'application', 'type': 'Microsoftgraphidentity'},
        'device': {'key': 'device', 'type': 'Microsoftgraphidentity'},
        'user': {'key': 'user', 'type': 'Microsoftgraphidentity'},
    }

    def __init__(self, application=None, device=None, user=None):
        super(MicrosoftgraphidentitySet, self).__init__()
        self.application = application
        self.device = device
        self.user = user
