# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdefaultColumnValue(Model):
    """defaultColumnValue.

    :param formula:
    :type formula: str
    :param value:
    :type value: str
    """

    _attribute_map = {
        'formula': {'key': 'formula', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
    }

    def __init__(self, formula=None, value=None):
        super(MicrosoftgraphdefaultColumnValue, self).__init__()
        self.formula = formula
        self.value = value
