# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookChartGridlinesFormat(Model):
    """MicrosoftgraphworkbookChartGridlinesFormat.

    :param id:
    :type id: str
    :param line:
    :type line: ~users.models.MicrosoftgraphworkbookChartLineFormat
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'line': {'key': 'line', 'type': 'MicrosoftgraphworkbookChartLineFormat'},
    }

    def __init__(self, id=None, line=None):
        super(MicrosoftgraphworkbookChartGridlinesFormat, self).__init__()
        self.id = id
        self.line = line
