# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphmobileAppTroubleshootingHistoryItem(Model):
    """mobileAppTroubleshootingHistoryItem.

    :param occurrence_date_time: Time when the history item occurred.
    :type occurrence_date_time: datetime
    """

    _attribute_map = {
        'occurrence_date_time': {'key': 'occurrenceDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, occurrence_date_time=None):
        super(MicrosoftgraphmobileAppTroubleshootingHistoryItem, self).__init__()
        self.occurrence_date_time = occurrence_date_time
