# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphautomaticRepliesSetting(Model):
    """automaticRepliesSetting.

    :param status: Possible values include: 'disabled', 'alwaysEnabled',
     'scheduled'
    :type status: str or ~users.models.enum
    :param external_audience: Possible values include: 'none', 'contactsOnly',
     'all'
    :type external_audience: str or ~users.models.enum
    :param scheduled_start_date_time:
    :type scheduled_start_date_time:
     ~users.models.MicrosoftgraphdateTimeTimeZone
    :param scheduled_end_date_time:
    :type scheduled_end_date_time:
     ~users.models.MicrosoftgraphdateTimeTimeZone
    :param internal_reply_message:
    :type internal_reply_message: str
    :param external_reply_message:
    :type external_reply_message: str
    """

    _attribute_map = {
        'status': {'key': 'status', 'type': 'str'},
        'external_audience': {'key': 'externalAudience', 'type': 'str'},
        'scheduled_start_date_time': {'key': 'scheduledStartDateTime', 'type': 'MicrosoftgraphdateTimeTimeZone'},
        'scheduled_end_date_time': {'key': 'scheduledEndDateTime', 'type': 'MicrosoftgraphdateTimeTimeZone'},
        'internal_reply_message': {'key': 'internalReplyMessage', 'type': 'str'},
        'external_reply_message': {'key': 'externalReplyMessage', 'type': 'str'},
    }

    def __init__(self, status=None, external_audience=None, scheduled_start_date_time=None, scheduled_end_date_time=None, internal_reply_message=None, external_reply_message=None):
        super(MicrosoftgraphautomaticRepliesSetting, self).__init__()
        self.status = status
        self.external_audience = external_audience
        self.scheduled_start_date_time = scheduled_start_date_time
        self.scheduled_end_date_time = scheduled_end_date_time
        self.internal_reply_message = internal_reply_message
        self.external_reply_message = external_reply_message
