# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphstoragePlanInformation(Model):
    """storagePlanInformation.

    :param upgrade_available:
    :type upgrade_available: bool
    """

    _attribute_map = {
        'upgrade_available': {'key': 'upgradeAvailable', 'type': 'bool'},
    }

    def __init__(self, upgrade_available=None):
        super(MicrosoftgraphstoragePlanInformation, self).__init__()
        self.upgrade_available = upgrade_available
