# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphitemActionSet(Model):
    """itemActionSet.

    :param comment:
    :type comment: ~users.models.MicrosoftgraphcommentAction
    :param create:
    :type create: object
    :param delete:
    :type delete: ~users.models.MicrosoftgraphdeleteAction
    :param edit:
    :type edit: object
    :param mention:
    :type mention: ~users.models.MicrosoftgraphmentionAction
    :param move:
    :type move: ~users.models.MicrosoftgraphmoveAction
    :param rename:
    :type rename: ~users.models.MicrosoftgraphrenameAction
    :param restore:
    :type restore: object
    :param share:
    :type share: ~users.models.MicrosoftgraphshareAction
    :param version:
    :type version: ~users.models.MicrosoftgraphversionAction
    """

    _attribute_map = {
        'comment': {'key': 'comment', 'type': 'MicrosoftgraphcommentAction'},
        'create': {'key': 'create', 'type': 'object'},
        'delete': {'key': 'delete', 'type': 'MicrosoftgraphdeleteAction'},
        'edit': {'key': 'edit', 'type': 'object'},
        'mention': {'key': 'mention', 'type': 'MicrosoftgraphmentionAction'},
        'move': {'key': 'move', 'type': 'MicrosoftgraphmoveAction'},
        'rename': {'key': 'rename', 'type': 'MicrosoftgraphrenameAction'},
        'restore': {'key': 'restore', 'type': 'object'},
        'share': {'key': 'share', 'type': 'MicrosoftgraphshareAction'},
        'version': {'key': 'version', 'type': 'MicrosoftgraphversionAction'},
    }

    def __init__(self, comment=None, create=None, delete=None, edit=None, mention=None, move=None, rename=None, restore=None, share=None, version=None):
        super(MicrosoftgraphitemActionSet, self).__init__()
        self.comment = comment
        self.create = create
        self.delete = delete
        self.edit = edit
        self.mention = mention
        self.move = move
        self.rename = rename
        self.restore = restore
        self.share = share
        self.version = version
