# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphcurrencyColumn(Model):
    """currencyColumn.

    :param locale:
    :type locale: str
    """

    _attribute_map = {
        'locale': {'key': 'locale', 'type': 'str'},
    }

    def __init__(self, locale=None):
        super(MicrosoftgraphcurrencyColumn, self).__init__()
        self.locale = locale
