# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphassignedLicense(Model):
    """assignedLicense.

    :param disabled_plans:
    :type disabled_plans: list[str]
    :param sku_id:
    :type sku_id: str
    """

    _attribute_map = {
        'disabled_plans': {'key': 'disabledPlans', 'type': '[str]'},
        'sku_id': {'key': 'skuId', 'type': 'str'},
    }

    def __init__(self, disabled_plans=None, sku_id=None):
        super(MicrosoftgraphassignedLicense, self).__init__()
        self.disabled_plans = disabled_plans
        self.sku_id = sku_id
