# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookChartDataLabels(Model):
    """MicrosoftgraphworkbookChartDataLabels.

    :param id:
    :type id: str
    :param position:
    :type position: str
    :param separator:
    :type separator: str
    :param show_bubble_size:
    :type show_bubble_size: bool
    :param show_category_name:
    :type show_category_name: bool
    :param show_legend_key:
    :type show_legend_key: bool
    :param show_percentage:
    :type show_percentage: bool
    :param show_series_name:
    :type show_series_name: bool
    :param show_value:
    :type show_value: bool
    :param format:
    :type format: ~users.models.MicrosoftgraphworkbookChartDataLabelFormat
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'position': {'key': 'position', 'type': 'str'},
        'separator': {'key': 'separator', 'type': 'str'},
        'show_bubble_size': {'key': 'showBubbleSize', 'type': 'bool'},
        'show_category_name': {'key': 'showCategoryName', 'type': 'bool'},
        'show_legend_key': {'key': 'showLegendKey', 'type': 'bool'},
        'show_percentage': {'key': 'showPercentage', 'type': 'bool'},
        'show_series_name': {'key': 'showSeriesName', 'type': 'bool'},
        'show_value': {'key': 'showValue', 'type': 'bool'},
        'format': {'key': 'format', 'type': 'MicrosoftgraphworkbookChartDataLabelFormat'},
    }

    def __init__(self, id=None, position=None, separator=None, show_bubble_size=None, show_category_name=None, show_legend_key=None, show_percentage=None, show_series_name=None, show_value=None, format=None):
        super(MicrosoftgraphworkbookChartDataLabels, self).__init__()
        self.id = id
        self.position = position
        self.separator = separator
        self.show_bubble_size = show_bubble_size
        self.show_category_name = show_category_name
        self.show_legend_key = show_legend_key
        self.show_percentage = show_percentage
        self.show_series_name = show_series_name
        self.show_value = show_value
        self.format = format
