# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdocumentComment(Model):
    """MicrosoftgraphdocumentComment.

    :param id:
    :type id: str
    :param content:
    :type content: str
    :param replies:
    :type replies: list[~users.models.MicrosoftgraphdocumentCommentReply]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'content': {'key': 'content', 'type': 'str'},
        'replies': {'key': 'replies', 'type': '[MicrosoftgraphdocumentCommentReply]'},
    }

    def __init__(self, id=None, content=None, replies=None):
        super(MicrosoftgraphdocumentComment, self).__init__()
        self.id = id
        self.content = content
        self.replies = replies
