# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphfileSystemInfo(Model):
    """fileSystemInfo.

    :param created_date_time:
    :type created_date_time: datetime
    :param last_accessed_date_time:
    :type last_accessed_date_time: datetime
    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    """

    _attribute_map = {
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'last_accessed_date_time': {'key': 'lastAccessedDateTime', 'type': 'iso-8601'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, created_date_time=None, last_accessed_date_time=None, last_modified_date_time=None):
        super(MicrosoftgraphfileSystemInfo, self).__init__()
        self.created_date_time = created_date_time
        self.last_accessed_date_time = last_accessed_date_time
        self.last_modified_date_time = last_modified_date_time
