# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphscopedRoleMembership(Model):
    """MicrosoftgraphscopedRoleMembership.

    :param id:
    :type id: str
    :param role_id:
    :type role_id: str
    :param administrative_unit_id:
    :type administrative_unit_id: str
    :param role_member_info:
    :type role_member_info: ~users.models.Microsoftgraphidentity
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'role_id': {'key': 'roleId', 'type': 'str'},
        'administrative_unit_id': {'key': 'administrativeUnitId', 'type': 'str'},
        'role_member_info': {'key': 'roleMemberInfo', 'type': 'Microsoftgraphidentity'},
    }

    def __init__(self, id=None, role_id=None, administrative_unit_id=None, role_member_info=None):
        super(MicrosoftgraphscopedRoleMembership, self).__init__()
        self.id = id
        self.role_id = role_id
        self.administrative_unit_id = administrative_unit_id
        self.role_member_info = role_member_info
