# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphopenShift(Model):
    """MicrosoftgraphopenShift.

    :param id:
    :type id: str
    :param created_date_time:
    :type created_date_time: datetime
    :param last_modified_date_time:
    :type last_modified_date_time: datetime
    :param last_modified_by:
    :type last_modified_by: ~users.models.MicrosoftgraphidentitySet
    :param shared_open_shift:
    :type shared_open_shift: ~users.models.MicrosoftgraphopenShiftItem
    :param draft_open_shift:
    :type draft_open_shift: ~users.models.MicrosoftgraphopenShiftItem
    :param scheduling_group_id:
    :type scheduling_group_id: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'last_modified_date_time': {'key': 'lastModifiedDateTime', 'type': 'iso-8601'},
        'last_modified_by': {'key': 'lastModifiedBy', 'type': 'MicrosoftgraphidentitySet'},
        'shared_open_shift': {'key': 'sharedOpenShift', 'type': 'MicrosoftgraphopenShiftItem'},
        'draft_open_shift': {'key': 'draftOpenShift', 'type': 'MicrosoftgraphopenShiftItem'},
        'scheduling_group_id': {'key': 'schedulingGroupId', 'type': 'str'},
    }

    def __init__(self, id=None, created_date_time=None, last_modified_date_time=None, last_modified_by=None, shared_open_shift=None, draft_open_shift=None, scheduling_group_id=None):
        super(MicrosoftgraphopenShift, self).__init__()
        self.id = id
        self.created_date_time = created_date_time
        self.last_modified_date_time = last_modified_date_time
        self.last_modified_by = last_modified_by
        self.shared_open_shift = shared_open_shift
        self.draft_open_shift = draft_open_shift
        self.scheduling_group_id = scheduling_group_id
