# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphwindowsProtectionState(Model):
    """MicrosoftgraphwindowsProtectionState.

    :param id:
    :type id: str
    :param malware_protection_enabled: Anti malware is enabled or not
    :type malware_protection_enabled: bool
    :param device_state: Possible values include: 'clean', 'fullScanPending',
     'rebootPending', 'manualStepsPending', 'offlineScanPending', 'critical'
    :type device_state: str or ~users.models.enum
    :param real_time_protection_enabled: Real time protection is enabled or
     not?
    :type real_time_protection_enabled: bool
    :param network_inspection_system_enabled: Network inspection system
     enabled or not?
    :type network_inspection_system_enabled: bool
    :param quick_scan_overdue: Quick scan overdue or not?
    :type quick_scan_overdue: bool
    :param full_scan_overdue: Full scan overdue or not?
    :type full_scan_overdue: bool
    :param signature_update_overdue: Signature out of date or not?
    :type signature_update_overdue: bool
    :param reboot_required: Reboot required or not?
    :type reboot_required: bool
    :param full_scan_required: Full scan required or not?
    :type full_scan_required: bool
    :param engine_version: Current endpoint protection engine's version
    :type engine_version: str
    :param signature_version: Current malware definitions version
    :type signature_version: str
    :param anti_malware_version: Current anti malware version
    :type anti_malware_version: str
    :param last_quick_scan_date_time: Last quick scan datetime
    :type last_quick_scan_date_time: datetime
    :param last_full_scan_date_time: Last quick scan datetime
    :type last_full_scan_date_time: datetime
    :param last_quick_scan_signature_version: Last quick scan signature
     version
    :type last_quick_scan_signature_version: str
    :param last_full_scan_signature_version: Last full scan signature version
    :type last_full_scan_signature_version: str
    :param last_reported_date_time: Last device health status reported time
    :type last_reported_date_time: datetime
    :param detected_malware_state:
    :type detected_malware_state:
     list[~users.models.MicrosoftgraphwindowsDeviceMalwareState]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'malware_protection_enabled': {'key': 'malwareProtectionEnabled', 'type': 'bool'},
        'device_state': {'key': 'deviceState', 'type': 'str'},
        'real_time_protection_enabled': {'key': 'realTimeProtectionEnabled', 'type': 'bool'},
        'network_inspection_system_enabled': {'key': 'networkInspectionSystemEnabled', 'type': 'bool'},
        'quick_scan_overdue': {'key': 'quickScanOverdue', 'type': 'bool'},
        'full_scan_overdue': {'key': 'fullScanOverdue', 'type': 'bool'},
        'signature_update_overdue': {'key': 'signatureUpdateOverdue', 'type': 'bool'},
        'reboot_required': {'key': 'rebootRequired', 'type': 'bool'},
        'full_scan_required': {'key': 'fullScanRequired', 'type': 'bool'},
        'engine_version': {'key': 'engineVersion', 'type': 'str'},
        'signature_version': {'key': 'signatureVersion', 'type': 'str'},
        'anti_malware_version': {'key': 'antiMalwareVersion', 'type': 'str'},
        'last_quick_scan_date_time': {'key': 'lastQuickScanDateTime', 'type': 'iso-8601'},
        'last_full_scan_date_time': {'key': 'lastFullScanDateTime', 'type': 'iso-8601'},
        'last_quick_scan_signature_version': {'key': 'lastQuickScanSignatureVersion', 'type': 'str'},
        'last_full_scan_signature_version': {'key': 'lastFullScanSignatureVersion', 'type': 'str'},
        'last_reported_date_time': {'key': 'lastReportedDateTime', 'type': 'iso-8601'},
        'detected_malware_state': {'key': 'detectedMalwareState', 'type': '[MicrosoftgraphwindowsDeviceMalwareState]'},
    }

    def __init__(self, id=None, malware_protection_enabled=None, device_state=None, real_time_protection_enabled=None, network_inspection_system_enabled=None, quick_scan_overdue=None, full_scan_overdue=None, signature_update_overdue=None, reboot_required=None, full_scan_required=None, engine_version=None, signature_version=None, anti_malware_version=None, last_quick_scan_date_time=None, last_full_scan_date_time=None, last_quick_scan_signature_version=None, last_full_scan_signature_version=None, last_reported_date_time=None, detected_malware_state=None):
        super(MicrosoftgraphwindowsProtectionState, self).__init__()
        self.id = id
        self.malware_protection_enabled = malware_protection_enabled
        self.device_state = device_state
        self.real_time_protection_enabled = real_time_protection_enabled
        self.network_inspection_system_enabled = network_inspection_system_enabled
        self.quick_scan_overdue = quick_scan_overdue
        self.full_scan_overdue = full_scan_overdue
        self.signature_update_overdue = signature_update_overdue
        self.reboot_required = reboot_required
        self.full_scan_required = full_scan_required
        self.engine_version = engine_version
        self.signature_version = signature_version
        self.anti_malware_version = anti_malware_version
        self.last_quick_scan_date_time = last_quick_scan_date_time
        self.last_full_scan_date_time = last_full_scan_date_time
        self.last_quick_scan_signature_version = last_quick_scan_signature_version
        self.last_full_scan_signature_version = last_full_scan_signature_version
        self.last_reported_date_time = last_reported_date_time
        self.detected_malware_state = detected_malware_state
