# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphprovisionedPlan(Model):
    """provisionedPlan.

    :param capability_status:
    :type capability_status: str
    :param provisioning_status:
    :type provisioning_status: str
    :param service:
    :type service: str
    """

    _attribute_map = {
        'capability_status': {'key': 'capabilityStatus', 'type': 'str'},
        'provisioning_status': {'key': 'provisioningStatus', 'type': 'str'},
        'service': {'key': 'service', 'type': 'str'},
    }

    def __init__(self, capability_status=None, provisioning_status=None, service=None):
        super(MicrosoftgraphprovisionedPlan, self).__init__()
        self.capability_status = capability_status
        self.provisioning_status = provisioning_status
        self.service = service
