# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphtypedEmailAddress(Model):
    """MicrosoftgraphtypedEmailAddress.

    :param name:
    :type name: str
    :param address:
    :type address: str
    :param type: Possible values include: 'unknown', 'work', 'personal',
     'main', 'other'
    :type type: str or ~users.models.enum
    :param other_label:
    :type other_label: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'address': {'key': 'address', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'other_label': {'key': 'otherLabel', 'type': 'str'},
    }

    def __init__(self, name=None, address=None, type=None, other_label=None):
        super(MicrosoftgraphtypedEmailAddress, self).__init__()
        self.name = name
        self.address = address
        self.type = type
        self.other_label = other_label
