# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphmailboxSettings(Model):
    """mailboxSettings.

    :param automatic_replies_setting:
    :type automatic_replies_setting:
     ~users.models.MicrosoftgraphautomaticRepliesSetting
    :param archive_folder:
    :type archive_folder: str
    :param time_zone:
    :type time_zone: str
    :param language:
    :type language: ~users.models.MicrosoftgraphlocaleInfo
    :param delegate_meeting_message_delivery_options: Possible values include:
     'sendToDelegateAndInformationToPrincipal', 'sendToDelegateAndPrincipal',
     'sendToDelegateOnly'
    :type delegate_meeting_message_delivery_options: str or ~users.models.enum
    :param working_hours:
    :type working_hours: ~users.models.MicrosoftgraphworkingHours
    :param date_format:
    :type date_format: str
    :param time_format:
    :type time_format: str
    """

    _attribute_map = {
        'automatic_replies_setting': {'key': 'automaticRepliesSetting', 'type': 'MicrosoftgraphautomaticRepliesSetting'},
        'archive_folder': {'key': 'archiveFolder', 'type': 'str'},
        'time_zone': {'key': 'timeZone', 'type': 'str'},
        'language': {'key': 'language', 'type': 'MicrosoftgraphlocaleInfo'},
        'delegate_meeting_message_delivery_options': {'key': 'delegateMeetingMessageDeliveryOptions', 'type': 'str'},
        'working_hours': {'key': 'workingHours', 'type': 'MicrosoftgraphworkingHours'},
        'date_format': {'key': 'dateFormat', 'type': 'str'},
        'time_format': {'key': 'timeFormat', 'type': 'str'},
    }

    def __init__(self, automatic_replies_setting=None, archive_folder=None, time_zone=None, language=None, delegate_meeting_message_delivery_options=None, working_hours=None, date_format=None, time_format=None):
        super(MicrosoftgraphmailboxSettings, self).__init__()
        self.automatic_replies_setting = automatic_replies_setting
        self.archive_folder = archive_folder
        self.time_zone = time_zone
        self.language = language
        self.delegate_meeting_message_delivery_options = delegate_meeting_message_delivery_options
        self.working_hours = working_hours
        self.date_format = date_format
        self.time_format = time_format
