# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphonPremisesExtensionAttributes(Model):
    """onPremisesExtensionAttributes.

    :param extension_attribute1:
    :type extension_attribute1: str
    :param extension_attribute2:
    :type extension_attribute2: str
    :param extension_attribute3:
    :type extension_attribute3: str
    :param extension_attribute4:
    :type extension_attribute4: str
    :param extension_attribute5:
    :type extension_attribute5: str
    :param extension_attribute6:
    :type extension_attribute6: str
    :param extension_attribute7:
    :type extension_attribute7: str
    :param extension_attribute8:
    :type extension_attribute8: str
    :param extension_attribute9:
    :type extension_attribute9: str
    :param extension_attribute10:
    :type extension_attribute10: str
    :param extension_attribute11:
    :type extension_attribute11: str
    :param extension_attribute12:
    :type extension_attribute12: str
    :param extension_attribute13:
    :type extension_attribute13: str
    :param extension_attribute14:
    :type extension_attribute14: str
    :param extension_attribute15:
    :type extension_attribute15: str
    """

    _attribute_map = {
        'extension_attribute1': {'key': 'extensionAttribute1', 'type': 'str'},
        'extension_attribute2': {'key': 'extensionAttribute2', 'type': 'str'},
        'extension_attribute3': {'key': 'extensionAttribute3', 'type': 'str'},
        'extension_attribute4': {'key': 'extensionAttribute4', 'type': 'str'},
        'extension_attribute5': {'key': 'extensionAttribute5', 'type': 'str'},
        'extension_attribute6': {'key': 'extensionAttribute6', 'type': 'str'},
        'extension_attribute7': {'key': 'extensionAttribute7', 'type': 'str'},
        'extension_attribute8': {'key': 'extensionAttribute8', 'type': 'str'},
        'extension_attribute9': {'key': 'extensionAttribute9', 'type': 'str'},
        'extension_attribute10': {'key': 'extensionAttribute10', 'type': 'str'},
        'extension_attribute11': {'key': 'extensionAttribute11', 'type': 'str'},
        'extension_attribute12': {'key': 'extensionAttribute12', 'type': 'str'},
        'extension_attribute13': {'key': 'extensionAttribute13', 'type': 'str'},
        'extension_attribute14': {'key': 'extensionAttribute14', 'type': 'str'},
        'extension_attribute15': {'key': 'extensionAttribute15', 'type': 'str'},
    }

    def __init__(self, extension_attribute1=None, extension_attribute2=None, extension_attribute3=None, extension_attribute4=None, extension_attribute5=None, extension_attribute6=None, extension_attribute7=None, extension_attribute8=None, extension_attribute9=None, extension_attribute10=None, extension_attribute11=None, extension_attribute12=None, extension_attribute13=None, extension_attribute14=None, extension_attribute15=None):
        super(MicrosoftgraphonPremisesExtensionAttributes, self).__init__()
        self.extension_attribute1 = extension_attribute1
        self.extension_attribute2 = extension_attribute2
        self.extension_attribute3 = extension_attribute3
        self.extension_attribute4 = extension_attribute4
        self.extension_attribute5 = extension_attribute5
        self.extension_attribute6 = extension_attribute6
        self.extension_attribute7 = extension_attribute7
        self.extension_attribute8 = extension_attribute8
        self.extension_attribute9 = extension_attribute9
        self.extension_attribute10 = extension_attribute10
        self.extension_attribute11 = extension_attribute11
        self.extension_attribute12 = extension_attribute12
        self.extension_attribute13 = extension_attribute13
        self.extension_attribute14 = extension_attribute14
        self.extension_attribute15 = extension_attribute15
