# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkingHours(Model):
    """workingHours.

    :param days_of_week:
    :type days_of_week: list[str]
    :param start_time:
    :type start_time: str
    :param end_time:
    :type end_time: str
    :param time_zone:
    :type time_zone: ~users.models.MicrosoftgraphtimeZoneBase
    """

    _attribute_map = {
        'days_of_week': {'key': 'daysOfWeek', 'type': '[str]'},
        'start_time': {'key': 'startTime', 'type': 'str'},
        'end_time': {'key': 'endTime', 'type': 'str'},
        'time_zone': {'key': 'timeZone', 'type': 'MicrosoftgraphtimeZoneBase'},
    }

    def __init__(self, days_of_week=None, start_time=None, end_time=None, time_zone=None):
        super(MicrosoftgraphworkingHours, self).__init__()
        self.days_of_week = days_of_week
        self.start_time = start_time
        self.end_time = end_time
        self.time_zone = time_zone
