# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphplannerBucketTaskBoardTaskFormat(Model):
    """MicrosoftgraphplannerBucketTaskBoardTaskFormat.

    :param id:
    :type id: str
    :param order_hint:
    :type order_hint: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'order_hint': {'key': 'orderHint', 'type': 'str'},
    }

    def __init__(self, id=None, order_hint=None):
        super(MicrosoftgraphplannerBucketTaskBoardTaskFormat, self).__init__()
        self.id = id
        self.order_hint = order_hint
