# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphworkbookChartLineFormat(Model):
    """MicrosoftgraphworkbookChartLineFormat.

    :param id:
    :type id: str
    :param color:
    :type color: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'color': {'key': 'color', 'type': 'str'},
    }

    def __init__(self, id=None, color=None):
        super(MicrosoftgraphworkbookChartLineFormat, self).__init__()
        self.id = id
        self.color = color
