# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphmeetingParticipantInfo(Model):
    """meetingParticipantInfo.

    :param identity:
    :type identity: ~users.models.MicrosoftgraphidentitySet
    :param upn:
    :type upn: str
    """

    _attribute_map = {
        'identity': {'key': 'identity', 'type': 'MicrosoftgraphidentitySet'},
        'upn': {'key': 'upn', 'type': 'str'},
    }

    def __init__(self, identity=None, upn=None):
        super(MicrosoftgraphmeetingParticipantInfo, self).__init__()
        self.identity = identity
        self.upn = upn
