# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphdirectoryObject(Model):
    """MicrosoftgraphdirectoryObject.

    :param id:
    :type id: str
    :param deleted_date_time:
    :type deleted_date_time: datetime
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'deleted_date_time': {'key': 'deletedDateTime', 'type': 'iso-8601'},
    }

    def __init__(self, id=None, deleted_date_time=None):
        super(MicrosoftgraphdirectoryObject, self).__init__()
        self.id = id
        self.deleted_date_time = deleted_date_time
