# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Microsoftgraphcommand(Model):
    """Microsoftgraphcommand.

    :param id:
    :type id: str
    :param status:
    :type status: str
    :param type:
    :type type: str
    :param app_service_name:
    :type app_service_name: str
    :param package_family_name:
    :type package_family_name: str
    :param error:
    :type error: str
    :param payload:
    :type payload: object
    :param permission_ticket:
    :type permission_ticket: str
    :param post_back_uri:
    :type post_back_uri: str
    :param responsepayload:
    :type responsepayload: ~users.models.MicrosoftgraphpayloadResponse
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'status': {'key': 'Status', 'type': 'str'},
        'type': {'key': 'Type', 'type': 'str'},
        'app_service_name': {'key': 'AppServiceName', 'type': 'str'},
        'package_family_name': {'key': 'PackageFamilyName', 'type': 'str'},
        'error': {'key': 'Error', 'type': 'str'},
        'payload': {'key': 'Payload', 'type': 'object'},
        'permission_ticket': {'key': 'PermissionTicket', 'type': 'str'},
        'post_back_uri': {'key': 'PostBackUri', 'type': 'str'},
        'responsepayload': {'key': 'responsepayload', 'type': 'MicrosoftgraphpayloadResponse'},
    }

    def __init__(self, id=None, status=None, type=None, app_service_name=None, package_family_name=None, error=None, payload=None, permission_ticket=None, post_back_uri=None, responsepayload=None):
        super(Microsoftgraphcommand, self).__init__()
        self.id = id
        self.status = status
        self.type = type
        self.app_service_name = app_service_name
        self.package_family_name = package_family_name
        self.error = error
        self.payload = payload
        self.permission_ticket = permission_ticket
        self.post_back_uri = post_back_uri
        self.responsepayload = responsepayload
