# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphchatMessagePolicyViolationPolicyTip(Model):
    """chatMessagePolicyViolationPolicyTip.

    :param general_text:
    :type general_text: str
    :param compliance_url:
    :type compliance_url: str
    :param matched_condition_descriptions:
    :type matched_condition_descriptions: list[str]
    """

    _attribute_map = {
        'general_text': {'key': 'generalText', 'type': 'str'},
        'compliance_url': {'key': 'complianceUrl', 'type': 'str'},
        'matched_condition_descriptions': {'key': 'matchedConditionDescriptions', 'type': '[str]'},
    }

    def __init__(self, general_text=None, compliance_url=None, matched_condition_descriptions=None):
        super(MicrosoftgraphchatMessagePolicyViolationPolicyTip, self).__init__()
        self.general_text = general_text
        self.compliance_url = compliance_url
        self.matched_condition_descriptions = matched_condition_descriptions
