# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphinformationProtection(Model):
    """MicrosoftgraphinformationProtection.

    :param id:
    :type id: str
    :param policy:
    :type policy: ~users.models.MicrosoftgraphinformationProtectionPolicy
    :param sensitivity_labels:
    :type sensitivity_labels:
     list[~users.models.MicrosoftgraphsensitivityLabel]
    :param sensitivity_policy_settings:
    :type sensitivity_policy_settings:
     ~users.models.MicrosoftgraphsensitivityPolicySettings
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'policy': {'key': 'policy', 'type': 'MicrosoftgraphinformationProtectionPolicy'},
        'sensitivity_labels': {'key': 'sensitivityLabels', 'type': '[MicrosoftgraphsensitivityLabel]'},
        'sensitivity_policy_settings': {'key': 'sensitivityPolicySettings', 'type': 'MicrosoftgraphsensitivityPolicySettings'},
    }

    def __init__(self, id=None, policy=None, sensitivity_labels=None, sensitivity_policy_settings=None):
        super(MicrosoftgraphinformationProtection, self).__init__()
        self.id = id
        self.policy = policy
        self.sensitivity_labels = sensitivity_labels
        self.sensitivity_policy_settings = sensitivity_policy_settings
