# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftgraphaudioConferencing(Model):
    """audioConferencing.

    :param conference_id:
    :type conference_id: str
    :param toll_number:
    :type toll_number: str
    :param toll_free_number:
    :type toll_free_number: str
    :param dialin_url:
    :type dialin_url: str
    """

    _attribute_map = {
        'conference_id': {'key': 'conferenceId', 'type': 'str'},
        'toll_number': {'key': 'tollNumber', 'type': 'str'},
        'toll_free_number': {'key': 'tollFreeNumber', 'type': 'str'},
        'dialin_url': {'key': 'dialinUrl', 'type': 'str'},
    }

    def __init__(self, conference_id=None, toll_number=None, toll_free_number=None, dialin_url=None):
        super(MicrosoftgraphaudioConferencing, self).__init__()
        self.conference_id = conference_id
        self.toll_number = toll_number
        self.toll_free_number = toll_free_number
        self.dialin_url = dialin_url
