# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Microsoftgraphnotification(Model):
    """Microsoftgraphnotification.

    :param id:
    :type id: str
    :param target_host_name:
    :type target_host_name: str
    :param expiration_date_time:
    :type expiration_date_time: datetime
    :param payload:
    :type payload: ~users.models.MicrosoftgraphpayloadTypes
    :param display_time_to_live:
    :type display_time_to_live: int
    :param priority: Possible values include: 'None', 'High', 'Low'
    :type priority: str or ~users.models.enum
    :param group_name:
    :type group_name: str
    :param target_policy:
    :type target_policy: ~users.models.MicrosoftgraphtargetPolicyEndpoints
    """

    _validation = {
        'display_time_to_live': {'maximum': 2147483647, 'minimum': -2147483648},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'target_host_name': {'key': 'targetHostName', 'type': 'str'},
        'expiration_date_time': {'key': 'expirationDateTime', 'type': 'iso-8601'},
        'payload': {'key': 'payload', 'type': 'MicrosoftgraphpayloadTypes'},
        'display_time_to_live': {'key': 'displayTimeToLive', 'type': 'int'},
        'priority': {'key': 'priority', 'type': 'str'},
        'group_name': {'key': 'groupName', 'type': 'str'},
        'target_policy': {'key': 'targetPolicy', 'type': 'MicrosoftgraphtargetPolicyEndpoints'},
    }

    def __init__(self, id=None, target_host_name=None, expiration_date_time=None, payload=None, display_time_to_live=None, priority=None, group_name=None, target_policy=None):
        super(Microsoftgraphnotification, self).__init__()
        self.id = id
        self.target_host_name = target_host_name
        self.expiration_date_time = expiration_date_time
        self.payload = payload
        self.display_time_to_live = display_time_to_live
        self.priority = priority
        self.group_name = group_name
        self.target_policy = target_policy
