# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model
from msrest.exceptions import HttpOperationError


class Odataerror(Model):
    """Odataerror.

    :param error:
    :type error: ~users.models.Odataerrormain
    """

    _validation = {
        'error': {'required': True},
    }

    _attribute_map = {
        'error': {'key': 'error', 'type': 'Odataerrormain'},
    }

    def __init__(self, error):
        super(Odataerror, self).__init__()
        self.error = error


class OdataerrorException(HttpOperationError):
    """Server responsed with exception of type: 'Odataerror'.

    :param deserialize: A deserializer
    :param response: Server response to be deserialized.
    """

    def __init__(self, deserialize, response, *args):

        super(OdataerrorException, self).__init__(deserialize, response, 'Odataerror', *args)
